'use client';
import{useEffect,useMemo,useState}from'react';

type Market={key:string;symbol:string;name:string;last:number|null};
type Trade={id:string;assetKey:string;side:'BUY'|'SELL';quantity:string;entryPrice:string;exitPrice:string|null;openedAt:number;closedAt:number|null;note:string|null};

export default function JournalPage(){
 const[markets,setMarkets]=useState<Market[]>([]),[trades,setTrades]=useState<Trade[]>([]),[assetKey,setAssetKey]=useState(''),[side,setSide]=useState<'BUY'|'SELL'>('BUY'),[quantity,setQuantity]=useState('1'),[entryPrice,setEntryPrice]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const openCount=useMemo(()=>trades.filter(t=>!t.closedAt).length,[trades]);
 const loadTrades=()=>fetch('/api/user-sync/paper-trades',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||`paper_${r.status}`);setTrades(d.trades||[]);});
 useEffect(()=>{Promise.all([fetch('/api/scanner',{cache:'no-store'}).then(r=>r.json()).then(d=>{const rows=(d.rows||d.data||[]) as Market[];setMarkets(rows);if(rows[0])setAssetKey(rows[0].key);}),loadTrades()]).catch(e=>setError(String(e))).finally(()=>setLoading(false));},[]);
 const selected=markets.find(m=>m.key===assetKey);
 useEffect(()=>{if(selected?.last!=null)setEntryPrice(String(selected.last));},[assetKey,markets]);
 const create=async()=>{setSaving(true);setError('');try{const r=await fetch('/api/user-sync/paper-trades',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetKey,side,quantity,entryPrice,note:note.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||`paper_${r.status}`);setNote('');await loadTrades();}catch(e){setError(String(e));}finally{setSaving(false);}};
 const closeTrade=async(t:Trade)=>{const exitPrice=window.prompt(`Prix de sortie pour ${t.assetKey}`);if(!exitPrice)return;try{const r=await fetch('/api/user-sync/paper-trades',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:t.id,exitPrice})});const d=await r.json();if(!r.ok)throw new Error(d.error||`paper_${r.status}`);await loadTrades();}catch(e){setError(String(e));}};
 const remove=async(t:Trade)=>{if(!window.confirm('Supprimer cette position simulée ?'))return;try{const r=await fetch(`/api/user-sync/paper-trades?id=${encodeURIComponent(t.id)}`,{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d.error||`paper_${r.status}`);await loadTrades();}catch(e){setError(String(e));}};
 return <main style={{maxWidth:1050,margin:'0 auto',padding:'32px 20px',fontFamily:'system-ui'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><p style={{opacity:.65,margin:0}}>COCKPIT MARCHÉS AI</p><h1 style={{margin:'4px 0'}}>Paper Trading & Journal</h1><p style={{opacity:.75}}>Simulation uniquement · aucun ordre réel exécuté · {openCount} position(s) ouverte(s)</p></div><a href="/" style={{color:'inherit'}}>← Retour au cockpit</a></header>{error&&<p style={{color:'#ff8c8c'}}>Synchronisation indisponible : {error}</p>}<section style={{margin:'20px 0',padding:16,border:'1px solid #334',borderRadius:14,display:'grid',gap:10}}><strong>Nouvelle position simulée</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><label>Actif<select value={assetKey} onChange={e=>setAssetKey(e.target.value)} style={{display:'block',width:'100%'}}>{markets.map(m=><option key={m.key} value={m.key}>{m.symbol||m.key}</option>)}</select></label><label>Sens<select value={side} onChange={e=>setSide(e.target.value as 'BUY'|'SELL')} style={{display:'block',width:'100%'}}><option>BUY</option><option>SELL</option></select></label><label>Quantité<input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal" style={{display:'block',width:'100%'}}/></label><label>Prix d’entrée<input value={entryPrice} onChange={e=>setEntryPrice(e.target.value)} inputMode="decimal" style={{display:'block',width:'100%'}}/></label></div><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={3} style={{display:'block',width:'100%'}}/></label><button disabled={saving||!assetKey||!entryPrice} onClick={()=>void create()} style={{width:'fit-content',padding:'9px 14px'}}>{saving?'Enregistrement…':'Ouvrir la position simulée'}</button></section>{loading?<p>Chargement…</p>:trades.length===0?<p>Aucune position simulée enregistrée.</p>:<section style={{display:'grid',gap:10}}>{trades.map(t=><article key={t.id} style={{padding:14,border:'1px solid #334',borderRadius:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{t.side} · {t.assetKey}</strong><p style={{margin:'6px 0'}}>Qté {t.quantity} · Entrée {t.entryPrice}{t.exitPrice?` · Sortie ${t.exitPrice}`:''}</p>{t.note&&<p style={{opacity:.75,margin:'6px 0'}}>{t.note}</p>}<small>{t.closedAt?'Clôturée':'Ouverte'} · {new Date(t.openedAt).toLocaleString('fr-BE')}</small></div><div style={{display:'flex',gap:8,alignItems:'start'}}>{!t.closedAt&&<button onClick={()=>void closeTrade(t)}>Clôturer</button>}<button onClick={()=>void remove(t)}>Supprimer</button></div></div></article>)}</section>}</main>;
}
