'use client';
import{useEffect,useMemo,useState}from'react';

type Event={id:string;assetKey:string;title:string;publisher:string;publishedAt:number;severity:'INFO'|'IMPORTANT'|'CRITIQUE';reason:string;link:string};
type Preferences={minimumSeverity:'INFO'|'IMPORTANT'|'CRITIQUE';watchedOnly:boolean;pushEnabled:boolean;quietHoursStart:string|null;quietHoursEnd:string|null};
type Snapshot={readNotificationIds?:string[];notificationPreferences?:Partial<Preferences>};
const defaults:Preferences={minimumSeverity:'IMPORTANT',watchedOnly:true,pushEnabled:false,quietHoursStart:null,quietHoursEnd:null};

export default function NotificationsPage(){
 const[events,setEvents]=useState<Event[]>([]),[severity,setSeverity]=useState('IMPORTANT'),[loading,setLoading]=useState(true),[read,setRead]=useState<Set<string>>(new Set()),[syncError,setSyncError]=useState(''),[prefs,setPrefs]=useState<Preferences>(defaults),[savingPrefs,setSavingPrefs]=useState(false),[prefsOpen,setPrefsOpen]=useState(false);
 useEffect(()=>{fetch('/api/user-sync/snapshot',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||`sync_${r.status}`);return d;}).then(d=>{const snapshot=(d.snapshot||{}) as Snapshot;setRead(new Set(Array.isArray(snapshot.readNotificationIds)?snapshot.readNotificationIds:[]));const next={...defaults,...(snapshot.notificationPreferences||{})};setPrefs(next);setSeverity(next.minimumSeverity);}).catch(e=>setSyncError(String(e)));},[]);
 useEffect(()=>{setLoading(true);fetch(`/api/news-alerts?severity=${encodeURIComponent(severity)}`).then(r=>r.json()).then(d=>setEvents(d.events||[])).finally(()=>setLoading(false));},[severity]);
 const unread=useMemo(()=>events.filter(e=>!read.has(e.id)).length,[events,read]);
 const mark=async(id:string)=>{if(read.has(id))return;try{const r=await fetch('/api/user-sync/notification-reads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventIds:[id]})});const d=await r.json();if(!r.ok)throw new Error(d.error||`sync_${r.status}`);setRead(prev=>new Set(prev).add(id));setSyncError('');}catch(e){setSyncError(String(e));}};
 const savePrefs=async()=>{setSavingPrefs(true);try{const r=await fetch('/api/user-sync/notification-preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(prefs)});const d=await r.json();if(!r.ok)throw new Error(d.error||`sync_${r.status}`);const next={...defaults,...(d.notificationPreferences||{})};setPrefs(next);setSeverity(next.minimumSeverity);setSyncError('');setPrefsOpen(false);}catch(e){setSyncError(String(e));}finally{setSavingPrefs(false);}};
 return <main style={{maxWidth:980,margin:'0 auto',padding:'32px 20px',fontFamily:'system-ui'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><p style={{opacity:.65,margin:0}}>COCKPIT MARCHÉS AI</p><h1 style={{margin:'4px 0'}}>Centre de notifications</h1><p style={{opacity:.75}}>News synchronisées avec l’application Flutter · {unread} non lue(s)</p>{syncError&&<p style={{color:'#ff8c8c',margin:'6px 0 0'}}>Synchronisation utilisateur indisponible : {syncError}</p>}</div><a href="/" style={{color:'inherit'}}>← Retour au cockpit</a></header>
  <section style={{display:'flex',gap:8,margin:'22px 0 10px',flexWrap:'wrap',alignItems:'center'}}>{['INFO','IMPORTANT','CRITIQUE'].map(level=><button key={level} onClick={()=>setSeverity(level)} style={{padding:'9px 14px',borderRadius:10,border:'1px solid #556',background:severity===level?'#243244':'transparent',color:'inherit'}}>{level}</button>)}<button onClick={()=>setPrefsOpen(v=>!v)} style={{marginLeft:'auto',padding:'9px 14px',borderRadius:10,border:'1px solid #556',background:prefsOpen?'#243244':'transparent',color:'inherit'}}>⚙ Préférences</button></section>
  {prefsOpen&&<section style={{margin:'10px 0 22px',padding:16,border:'1px solid #334',borderRadius:14,display:'grid',gap:12}}><strong>Préférences synchronisées Web ↔ Flutter</strong><label>Seuil minimum <select value={prefs.minimumSeverity} onChange={e=>setPrefs(p=>({...p,minimumSeverity:e.target.value as Preferences['minimumSeverity']}))} style={{marginLeft:8}}><option>INFO</option><option>IMPORTANT</option><option>CRITIQUE</option></select></label><label><input type="checkbox" checked={prefs.watchedOnly} onChange={e=>setPrefs(p=>({...p,watchedOnly:e.target.checked}))}/> Uniquement les actifs favoris</label><label><input type="checkbox" checked={prefs.pushEnabled} onChange={e=>setPrefs(p=>({...p,pushEnabled:e.target.checked}))}/> Notifications push dès qu’un fournisseur push est configuré</label><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><label>Silence début <input type="time" value={prefs.quietHoursStart||''} onChange={e=>setPrefs(p=>({...p,quietHoursStart:e.target.value||null}))}/></label><label>Silence fin <input type="time" value={prefs.quietHoursEnd||''} onChange={e=>setPrefs(p=>({...p,quietHoursEnd:e.target.value||null}))}/></label></div><button disabled={savingPrefs} onClick={()=>void savePrefs()} style={{width:'fit-content',padding:'9px 14px',borderRadius:10}}>{savingPrefs?'Enregistrement…':'Enregistrer les préférences'}</button></section>}
  {loading?<p>Chargement…</p>:events.length===0?<p>Aucune alerte pour ce filtre.</p>:<section style={{display:'grid',gap:12}}>{events.map(event=><article key={event.id} onClick={()=>void mark(event.id)} style={{padding:16,border:'1px solid #334',borderRadius:14,opacity:read.has(event.id)?.55:1,cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}}><div><strong>{event.severity} · {event.assetKey}</strong><h2 style={{fontSize:18,margin:'6px 0'}}>{event.title}</h2><p style={{margin:'4px 0',opacity:.75}}>{event.reason}</p><small>{event.publisher} · {new Date(event.publishedAt).toLocaleString('fr-BE')}</small></div><a href={event.link} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Ouvrir</a></div></article>)}</section>}
 </main>;
}
