const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function handler({account={customerId:'cus_owner'},ready=true,result={data:[],has_more:false},request=async()=>result}={}){const m={exports:{}};const deps={'server-only':{},'./invoice-history':{historicalInvoices:async()=>[]},'./plan-billing-store':{billingHost:'sites',getBillingAccount:async()=>account},'./plan-billing-config':{billingConfig:async()=>({ready,live:false})},'./plan-billing-core':{stripeRequest:request}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('lib/account-invoices.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>deps[n],m,m.exports);return m.exports.accountInvoices;}
const req=(q='')=>new Request('https://app.test/api/billing/invoices'+q);
const invoice={id:'in_own',customer:'cus_owner',livemode:false,currency:'eur',total:2400,amount_paid:2400,amount_remaining:0,status:'paid',total_taxes:[],total_discount_amounts:[],lines:{data:[]},hosted_invoice_url:'https://invoice.stripe.com/i/test',invoice_pdf:'https://pay.stripe.com/invoice/test/pdf',metadata:{secret:'do-not-send'},customer_email:'not-needed'};
test('anonymous callers never access Stripe',async()=>{let calls=0;const r=await handler({account:null,request:async()=>{calls++;}})(req());assert.equal(r.status,401);assert.equal(calls,0);assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
test('customer is taken only from the account and pagination remains scoped',async()=>{let path;const r=await handler({request:async p=>{path=p;return {data:[invoice],has_more:true};}})(req('?customer=cus_other&after=in_previous'));assert.equal(r.status,200);const q=new URL('https://api.test/'+path).searchParams;assert.equal(q.get('customer'),'cus_owner');assert.equal(q.get('starting_after'),'in_previous');const b=await r.json();assert.equal(b.next,'in_own');assert.equal(b.invoices[0].total,2400);assert.equal(b.invoices[0].test,true);assert.equal(b.invoices[0].pdf,invoice.invoice_pdf);assert(!JSON.stringify(b).includes('do-not-send'));assert(!JSON.stringify(b).includes('not-needed'));});
test('foreign customer or wrong mode fails closed',async()=>{for(const patch of [{customer:'cus_other'},{livemode:true}]){const r=await handler({result:{data:[{...invoice,...patch}]}})(req());assert.equal(r.status,503);assert(!(await r.text()).includes('in_own'));}});
test('invalid cursor cannot trigger upstream and missing customer is empty',async()=>{let calls=0;const request=async()=>{calls++;};assert.equal((await handler({request})(req('?after=../../secrets'))).status,400);const r=await handler({account:{customerId:null},request})(req());assert.deepEqual(await r.json(),{invoices:[],next:null});assert.equal(calls,0);});
test('unsafe document URLs and raw upstream errors are withheld',async()=>{const r=await handler({result:{data:[{...invoice,hosted_invoice_url:'javascript:alert(1)',invoice_pdf:'https://pay.stripe.com.evil.test/file'}]}})(req());const b=await r.json();assert.equal(b.invoices[0].url,null);assert.equal(b.invoices[0].pdf,null);const error=await handler({request:async()=>{throw Error('sk_sensitive');}})(req());assert.equal(error.status,503);assert(!(await error.text()).includes('sk_sensitive'));});
test('unconfigured billing does not query Stripe',async()=>{let calls=0;const r=await handler({ready:false,request:async()=>{calls++;}})(req());assert.equal(r.status,503);assert.equal(calls,0);});
