const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function compile(file,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n==='server-only')return {};if(n in deps)return deps[n];throw Error(n);},m,m.exports);return m.exports;}
const policy=compile('lib/ai-plan-policy.ts'),billing=compile('lib/plan-billing-core.ts',{'./plan-billing-config':{billingConfig:()=>({ready:false})}});
test('monthly quotas are consistent on both hosts and suspension wins over role',()=>{for(const p of ['free','DISCOVERY'])assert.equal(policy.aiPlanLimit(p,'ACTIVE','USER','ACTIVE'),5);for(const p of ['pro','PRO'])assert.equal(policy.aiPlanLimit(p,'ACTIVE','USER','ACTIVE'),100);for(const p of ['trader_plus','EXPERT'])assert.equal(policy.aiPlanLimit(p,'ACTIVE','USER','ACTIVE'),300);assert.equal(policy.aiPlanLimit('EXPERT','PAST_DUE','USER','ACTIVE'),5);assert.equal(policy.aiPlanLimit('EXPERT','ACTIVE','ADMIN','SUSPENDED'),0);assert.equal(policy.aiPlanLimit('DISCOVERY','ACTIVE','ADMIN','ACTIVE'),null);});
test('month window handles year rollover in UTC',()=>assert.deepEqual(policy.aiMonth(Date.UTC(2026,11,31,23,59)),{start:Date.UTC(2026,11,1),end:Date.UTC(2027,0,1)}));
test('unpaid checkout or trial never grants a paid plan',()=>{const sub={status:'active',items:{data:[{price:{id:'pro'}}]},latest_invoice:{status:'open'}};assert.equal(billing.subscriptionAccess(sub,'pro','expert').plan,'free');sub.latest_invoice.status='paid';assert.equal(billing.subscriptionAccess(sub,'pro','expert').plan,'pro');sub.status='trialing';assert.equal(billing.subscriptionAccess(sub,'pro','expert').plan,'free');sub.status='active';assert.equal(billing.subscriptionAccess(sub,'unknown','expert').plan,'free');});
test('signed webhook rejects tampered body, stale signature and missing signature',async()=>{const {createHmac}=require('node:crypto'),raw=JSON.stringify({type:'invoice.paid'}),t=Math.floor(Date.now()/1000),secret='test-only';const sig=`t=${t},v1=${createHmac('sha256',secret).update(t+'.'+raw).digest('hex')}`;assert.equal((await billing.verifyStripeEvent(raw,sig,secret)).type,'invoice.paid');await assert.rejects(billing.verifyStripeEvent(raw+' ',sig,secret));await assert.rejects(billing.verifyStripeEvent(raw,sig,secret,Date.now()+600000));await assert.rejects(billing.verifyStripeEvent(raw,'',secret));});
test('checkout trusts the signed-in account, never submitted identity or price',async()=>{let sent;const account={id:'verified-user',email:'verified@example.test',subscriptionId:null,customerId:null,status:'active'};const h=compile('lib/plan-billing-handlers.ts',{'./plan-billing-store':{getBillingAccount:async()=>account,billingHost:'vercel'},'./plan-billing-config':{billingConfig:()=>({ready:true,pro:'verified-price',expert:'expert'})},'./plan-billing-core':{...billing,stripeRequest:async(path,body)=>{sent=body;return{url:'https://checkout.stripe.com/test'};}}});const r=await h.checkout(new Request('https://app.test/api/billing/checkout',{method:'POST',headers:{origin:'https://app.test'},body:new URLSearchParams({plan:'pro',email:'attacker',price:'fake',user_id:'admin'})}));assert.equal(r.status,303);assert.equal(sent.get('client_reference_id'),'verified-user');assert.equal(sent.get('line_items[0][price]'),'verified-price');assert.equal(sent.get('customer_email'),'verified@example.test');});
if(fs.existsSync('db/schema.ts')&&fs.existsSync('drizzle/0004_bitter_misty_knight.sql'))test('SQLite reserves atomically and restores failed analysis credit',async()=>{const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(':memory:');db.exec('CREATE TABLE ai_monthly_usage(id TEXT PRIMARY KEY,used INTEGER NOT NULL DEFAULT 0)');const native={prepare:query=>({bind:(...values)=>({first:async()=>db.prepare(query).get(...values),run:async()=>db.prepare(query).run(...values)})})};const quota=compile('lib/ai-allowance.ts',{'cloudflare:workers':{env:{DB:native}},'./current-account':{getCurrentAccount:async()=>({identity:{email:'test@example.test'},membership:{plan:'free',subscriptionStatus:'inactive',role:'user',accountStatus:'active'}})},'./ai-plan-policy':policy,'./ai-allowance-types':compile('lib/ai-allowance-types.ts')});const reservations=await Promise.all(Array.from({length:5},()=>quota.reserveAIAllowance()));await assert.rejects(quota.reserveAIAllowance(),e=>e.limit===5);await quota.refundAIAllowance(reservations[0]);assert.equal((await quota.getAIAllowance()).remaining,1);await quota.reserveAIAllowance();assert.equal((await quota.getAIAllowance()).remaining,0);db.close();});
