import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('db/migrations/0008_web_auth_pairing.sql'),schema=read('db/schema.ts'),auth=read('lib/web-auth.ts'),identity=read('lib/user-identity.ts'),register=read('app/api/auth/register/route.ts'),login=read('app/api/auth/login/route.ts'),session=read('app/api/auth/session/route.ts'),pairCreate=read('app/api/mobile-pair/create/route.ts'),pairClaim=read('app/api/mobile-pair/claim/route.ts'),loginPage=read('app/login/page.tsx'),connectPage=read('app/mobile-connect/page.tsx'),mobileRepo=read('mobile/lib/features/auth/data/mobile_session_repository.dart'),mobileGate=read('mobile/lib/features/auth/presentation/mobile_connection_gate.dart');

test('standalone web credentials are durable and passwords are scrypt hashed',()=>{assert.match(migration,/web_credentials/);assert.match(schema,/webCredentials/);assert.match(auth,/scryptSync/);assert.match(auth,/timingSafeEqual/);assert.match(auth,/password_too_short/);assert.doesNotMatch(register,/password_hash|passwordHash/);});
test('web session uses secure HTTP-only signed cookie',()=>{assert.match(auth,/createHmac/);assert.match(auth,/WEB_SESSION_COOKIE/);assert.match(auth,/httpOnly:true/);assert.match(auth,/secure:true/);assert.match(auth,/sameSite:'lax'/);assert.match(identity,/readWebSession/);assert.match(identity,/source:'web'/);assert.match(session,/getSharedUserIdentity/);});
test('mobile pairing code is eight digits, short lived, hashed and one time',()=>{assert.match(migration,/mobile_pairing_codes/);assert.match(schema,/mobilePairingCodes/);assert.match(auth,/100000000/);assert.match(auth,/padStart\(8/);assert.match(auth,/5\*60\*1000/);assert.match(auth,/createHash\('sha256'/);assert.match(auth,/consumed_at is null/);assert.match(auth,/expires_at>/);assert.match(pairCreate,/createPairingCode/);assert.match(pairClaim,/consumePairingCode/);});
test('Chrome flow provides login and pairing without exposing mobile bearer token',()=>{assert.match(login,/authenticateWebUser/);assert.match(register,/registerWebUser/);assert.match(loginPage,/Créer un compte/);assert.match(connectPage,/Générer un code mobile/);assert.match(connectPage,/mobile-pair\/create/);assert.doesNotMatch(connectPage,/textarea|Jeton de connexion/);});
test('Flutter claims pairing code then stores only signed session token',()=>{assert.match(mobileRepo,/mobile-pair\/claim/);assert.match(mobileGate,/Code à 8 chiffres/);assert.match(mobileGate,/LengthLimitingTextInputFormatter\(8\)/);assert.match(mobileGate,/claimPairingCode/);assert.doesNotMatch(mobileGate,/Jeton mobile|Collez-le ici/);});
