import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('db/migrations/0006_billing_subscriptions.sql'),schema=read('db/schema.ts'),config=read('lib/billing-config.ts'),store=read('lib/billing-store.ts'),stripe=read('lib/stripe-rest.ts'),checkout=read('app/api/billing/checkout/route.ts'),portal=read('app/api/billing/portal/route.ts'),webhook=read('app/api/billing/webhook/route.ts'),status=read('app/api/billing/status/route.ts'),pricing=read('app/pricing/page.tsx'),terms=read('app/legal/terms/page.tsx'),privacy=read('app/legal/privacy/page.tsx'),risk=read('app/legal/risk-disclosure/page.tsx'),account=read('app/account/page.tsx'),exportRoute=read('app/api/account/export/route.ts'),deleteRoute=read('app/api/account/delete/route.ts'),readiness=read('lib/commercial-readiness.ts'),manifest=read('app/api/sync/manifest/route.ts');

test('billing schema is durable and idempotent',()=>{for(const name of['billing_subscriptions','billing_webhook_events']){assert.match(migration,new RegExp(name));assert.match(schema,new RegExp(name.replaceAll('_','')));}assert.match(migration,/CREATE TABLE IF NOT EXISTS/);assert.match(store,/@neondatabase\/serverless/);});
test('paid entitlement is server side and Stripe verified',()=>{assert.match(config,/FREE.*PRO.*INSTITUTIONAL/s);assert.match(checkout,/getSharedUserIdentity/);assert.match(checkout,/checkout\/sessions/);assert.match(checkout,/mode:'subscription'/);assert.match(checkout,/checkout_web_only/);assert.match(checkout,/STRIPE_PRICE_PRO|configuredPriceId/);assert.match(portal,/billing_portal\/sessions/);assert.match(webhook,/verifyStripeWebhook/);assert.match(webhook,/webhookEventProcessed/);assert.match(webhook,/customer\.subscription\.updated/);assert.match(status,/hasPaidEntitlement/);assert.doesNotMatch(pricing,/STRIPE_SECRET_KEY|STRIPE_WEBHOOK_SECRET|sk_live_|sk_test_/);});
test('Stripe integration uses signed webhooks and idempotency',()=>{assert.match(stripe,/timingSafeEqual/);assert.match(stripe,/age>300/);assert.match(stripe,/Idempotency-Key/);assert.match(webhook,/invalid_signature/);assert.match(store,/billing_webhook_events/);});
test('commercial pages disclose risk and billing terms',()=>{assert.match(pricing,/ne constitue ni un service de courtage/);assert.match(terms,/ne garantit aucun rendement/);assert.match(risk,/risque de perte partielle ou totale du capital/);assert.match(privacy,/Stripe/);});
test('GDPR export and erasure are authenticated and confirmed',()=>{assert.match(exportRoute,/getSharedUserIdentity/);assert.match(deleteRoute,/DELETE_MY_ACCOUNT/);assert.match(account,/Télécharger mes données/);assert.match(account,/Supprimer définitivement/);assert.match(deleteRoute,/active_subscription_must_be_cancelled/);});
test('commercial readiness fails closed on missing live configuration',()=>{for(const key of['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','STRIPE_PRICE_PRO','STRIPE_PRICE_INSTITUTIONAL','PUBLIC_APP_URL','LEGAL_OPERATOR_NAME','NEXT_PUBLIC_SUPPORT_EMAIL'])assert.match(readiness,new RegExp(key));assert.match(readiness,/stripeMode==='live'/);assert.match(readiness,/ready:blockers\.length===0/);});
test('manifest publishes commercial contract v2.5',()=>{assert.match(manifest,/schemaVersion:'2\.5\.0'/);for(const endpoint of['/api/billing/checkout','/api/billing/portal','/api/billing/webhook','/api/billing/status','/api/commercial-readiness','/api/account/export','/api/account/delete'])assert.match(manifest,new RegExp(endpoint.replaceAll('/','\\/')));assert.match(manifest,/mobileBillingLogic:'consume-entitlements-only'/);});
