const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function compile(file,deps={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',code)(name=>{if(name in deps)return deps[name];throw Error('Unexpected import '+name);},module,module.exports);return module.exports;}
const v=compile('lib/feedback-validation.ts');const request=(body,origin='https://app.test')=>new Request('https://app.test/api/feedback',{method:'POST',headers:{origin,host:'app.test'},body:JSON.stringify(body)});
test('reject cross-origin and oversized bodies before parsing',async()=>{await assert.rejects(v.readFeedbackBody(request({},'https://evil.test')),e=>e.status===403);await assert.rejects(v.readFeedbackBody(request('a'.repeat(800001))),e=>e.status===413);});
test('reject invalid fields, forged images and malformed base64',()=>{for(const input of [{message:'short',category:'bug'},{message:'Valid message',category:'admin'},{message:'Valid message',category:'bug',image:'data:image/svg+xml;base64,PHN2Zz4='},{message:'Valid message',category:'bug',image:'data:image/jpeg;base64,YQ=='}])assert.throws(()=>v.validateFeedback(input),e=>e.status===400);});
test('strip query strings and ignore forged identity',()=>{const x=v.validateFeedback({message:'  Valid message  ',category:'idea',page:'/account?token=secret',email:'admin@fake',status:'resolved'});assert.equal(x.message,'Valid message');assert.equal(x.page,'/account');assert.equal(x.email,undefined);assert.equal(x.status,undefined);});
test('all operations stop before storage when authentication fails',async()=>{let calls=0;const store={feedbackAuth:async()=>{throw new v.FeedbackError(401,'auth');}};for(const name of ['saveFeedback','listFeedback','updateFeedback','feedbackImage'])store[name]=async()=>{calls++;};const {handleFeedback}=compile('lib/feedback-handler.ts',{'./feedback-store':store,'./feedback-validation':v});for(const op of ['send','list','update','image'])assert.equal((await handleFeedback(request({}),op)).status,401);assert.equal(calls,0);});
test('admin operations require elevated authentication',async()=>{const seen=[];const store={feedbackAuth:async admin=>{seen.push(admin);throw new v.FeedbackError(403,'denied');}};const {handleFeedback}=compile('lib/feedback-handler.ts',{'./feedback-store':store,'./feedback-validation':v});for(const op of ['send','list','update','image'])await handleFeedback(request({}),op);assert.deepEqual(seen,[false,true,true,true]);});
test('unknown status never reaches update; private responses never cache',async()=>{let changed=false;const {handleFeedback}=compile('lib/feedback-handler.ts',{'./feedback-store':{feedbackAuth:async()=>({email:'verified@example.test'}),updateFeedback:async()=>{changed=true;}},'./feedback-validation':v});const r=await handleFeedback(request({id:'x',status:'invalid'}),'update');assert.equal(r.status,400);assert.equal(changed,false);assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
