const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function compile(file,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n==='server-only')return {};if(n in deps)return deps[n];throw Error(n);},m,m.exports);return m.exports;}
const content=compile('lib/public-content.ts',{zod:require('zod')}),http=compile('lib/ai-settings-http.ts'),account=compile('lib/account-request.ts');
let writes=0;
function route(overrides={}){return compile('app/api/admin/public-content/route.ts',{zod:require('zod'),'@/lib/public-content':content,'@/lib/account-request':account,'@/lib/ai-settings-http':http,'@/lib/ai-settings-store':{requireAISettingsOwner:async()=> 'owner'},'@/lib/public-content-service':{getPublicContent:async()=>({content:content.defaultContent,updatedAt:7}),savePublicContent:async()=>{writes++;return 8;}},'@/lib/ai-settings':{getAICredentials:async()=>({apiKey:'sk-not-real',model:'test'})},...overrides});}
function request(body,origin='https://app.test'){return new Request('https://app.test/api/admin/public-content',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});}
const publish=()=>({action:'publish',content:structuredClone(content.defaultContent),revision:7});
test('only owner can read or write public-page settings',async()=>{let accessed=false;const r=route({'@/lib/ai-settings-store':{requireAISettingsOwner:async()=>{throw new http.AISettingsError(403,'forbidden');}},'@/lib/public-content-service':{getPublicContent:async()=>{accessed=true;}}});assert.equal((await r.GET()).status,403);assert.equal((await r.POST(request(publish()))).status,403);assert.equal(accessed,false);});
test('cross-origin and oversized page mutations are rejected',async()=>{const r=route();assert.equal((await r.POST(request(publish(),'https://evil.test'))).status,403);assert.equal((await r.POST(request({text:'x'.repeat(350001)}))).status,413);});
test('invalid public email and unknown properties are rejected',async()=>{let b=publish();b.content.operator.email='javascript:alert(1)';assert.equal((await route().POST(request(b))).status,400);b=publish();b.content.secret='private';assert.equal((await route().POST(request(b))).status,400);});
test('stale revision cannot overwrite a newer publication',async()=>{const before=writes;const b=publish();b.revision=6;assert.equal((await route().POST(request(b))).status,409);assert.equal(writes,before);});
test('valid content is saved privately with a revision',async()=>{const r=await route().POST(request(publish()));assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.equal((await r.json()).updatedAt,8);});
test('AI produces a review draft without publishing and sanitizes upstream errors',async()=>{const before=writes,old=global.fetch;const body={action:'generate',locale:'fr',page:'about',content:content.defaultContent};try{global.fetch=async()=>Response.json({status:'completed',output:[{content:[{type:'output_text',text:'A reviewed public draft with sufficient content and SMARTDEV attribution.'}]}]});const r=await route().POST(request(body));assert.equal(r.status,200);assert((await r.json()).body.includes('SMARTDEV'));assert.equal(writes,before);global.fetch=async()=>new Response('SECRET_PROVIDER_ERROR',{status:401});const failed=await route().POST(request(body));assert.equal(failed.status,502);assert(!(await failed.text()).includes('SECRET'));assert.equal(writes,before);}finally{global.fetch=old;}});
