import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('db/migrations/0007_notification_delivery_log.sql'),schema=read('db/schema.ts'),mobile=read('lib/mobile-push-delivery.ts'),delivery=read('lib/push-delivery.ts'),store=read('lib/push-delivery-store.ts'),dispatch=read('app/api/notifications/dispatch/route.ts'),policy=read('lib/push-dispatch.ts'),workflow=read('.github/workflows/market-alert-dispatch.yml'),manifest=read('app/api/sync/manifest/route.ts');

test('push delivery is durable and deduplicated',()=>{assert.match(migration,/notification_deliveries/);assert.match(migration,/PRIMARY KEY\(user_id,event_id,device_id\)/);assert.match(schema,/notificationDeliveries/);assert.match(store,/deliveryRecorded/);assert.match(store,/recordDelivery/);assert.match(delivery,/deliveryRecorded/);assert.match(delivery,/recordDelivery/);});
test('FCM and APNs provider delivery is real and server side',()=>{assert.match(mobile,/firebase\.messaging/);assert.match(mobile,/oauth2\.googleapis\.com/);assert.match(mobile,/api\.push\.apple\.com/);assert.match(mobile,/http2/);assert.match(mobile,/APNS_BUNDLE_ID/);assert.doesNotMatch(mobile,/localStorage|sessionStorage/);});
test('provider delivery still uses personalized policy',()=>{assert.match(delivery,/buildPushDispatchPlan/);assert.match(policy,/alertEligibility/);assert.match(policy,/requirePush:true/);assert.match(delivery,/sendFcm/);assert.match(delivery,/sendApns/);});
test('real dispatch endpoint requires a server secret',()=>{assert.match(dispatch,/NOTIFICATION_DISPATCH_SECRET/);assert.match(dispatch,/authorization/);assert.match(dispatch,/Bearer/);assert.match(dispatch,/windowMinutes/);assert.match(dispatch,/listPushUserIds/);});
test('hourly scheduler calls protected production dispatch',()=>{assert.match(workflow,/cron: '17 \* \* \* \*'/);assert.match(workflow,/NOTIFICATION_DISPATCH_SECRET/);assert.match(workflow,/api\/notifications\/dispatch/);assert.match(workflow,/windowMinutes/);});
test('manifest advertises provider delivery in v2.5',()=>{assert.match(manifest,/provider-delivery-when-configured/);assert.match(manifest,/fcm:'server-delivery-ready'/);assert.match(manifest,/apns:'server-delivery-ready'/);assert.match(manifest,/notification_deliveries/);});
