const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function compile(file,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n==='server-only')return {};if(n in deps)return deps[n];throw Error(n);},m,m.exports);return m.exports;}
const errors=compile('lib/ai-settings-http.ts'),policy=compile('lib/stripe-test-policy.ts'),http=compile('lib/stripe-settings-http.ts',{'./ai-settings-http':errors,'./stripe-test-policy':policy});
const key='rk_test_1234567890123456',webhook='whsec_1234567890123456';
function req(body,origin='https://app.test'){return new Request('https://app.test/api/admin/stripe-settings',{method:'POST',headers:{origin},body:JSON.stringify(body)});}
test('live and publishable keys, cross-origin writes and oversized payloads are rejected',async()=>{for(const apiKey of ['rk_live_1234567890123456','sk_live_1234567890123456','pk_test_1234567890123456'])await assert.rejects(http.readStripeBody(req({action:'save',apiKey,webhookSecret:webhook})),e=>e.code==='test_key_required');await assert.rejects(http.readStripeBody(req({},'https://evil.test')),e=>e.status===403);await assert.rejects(http.readStripeBody(req({apiKey:'a'.repeat(6001)})),e=>e.status===413);});
test('unauthorized requests never touch secrets, storage or Stripe',async()=>{let touched=false;const route=compile('app/api/admin/stripe-settings/route.ts',{'@/lib/ai-settings-store':{requireAISettingsOwner:async()=>{throw new errors.AISettingsError(403,'forbidden');}},'@/lib/ai-settings-http':errors,'@/lib/stripe-settings':{getStripeSecrets:async()=>{touched=true;},stripeSettingsStatus:async()=>{touched=true;}},'@/lib/stripe-settings-http':http,'@/lib/stripe-test-policy':policy});assert.equal((await route.GET()).status,403);assert.equal((await route.POST(req({}))).status,403);assert.equal(touched,false);});
test('failed connection cannot overwrite saved configuration or expose provider errors',async()=>{let saved=false;const route=compile('app/api/admin/stripe-settings/route.ts',{'@/lib/ai-settings-store':{requireAISettingsOwner:async()=> 'owner'},'@/lib/ai-settings-http':errors,'@/lib/stripe-settings':{getStripeSecrets:async()=>({apiKey:key,webhookSecret:webhook}),saveStripeSecrets:async()=>{saved=true;}},'@/lib/stripe-settings-http':{...http,testStripeKey:async()=>{throw new Error('provider response with secret');}},'@/lib/stripe-test-policy':policy});const r=await route.POST(req({action:'save',apiKey:key,webhookSecret:webhook}));assert.equal(r.status,503);assert.equal(saved,false);assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.deepEqual(await r.json(),{error:'settings_unavailable'});});
test('saved secrets are encrypted and never returned by status',async()=>{const crypto=compile('lib/stripe-secret-crypto.ts'),previous=process.env.AI_SETTINGS_ENCRYPTION_KEY;process.env.AI_SETTINGS_ENCRYPTION_KEY='test-encryption-secret-'.repeat(3);let row;const settings=compile('lib/stripe-settings.ts',{'./stripe-settings-store':{readStripeSettings:async()=>row,writeStripeSettings:async encrypted=>{row={encrypted_key:encrypted};}},'./stripe-secret-crypto':crypto,'./stripe-test-policy':policy});try{await settings.saveStripeSecrets({apiKey:key,webhookSecret:webhook},'owner');assert(!row.encrypted_key.includes(key));assert(!row.encrypted_key.includes(webhook));assert.deepEqual(await settings.getStripeSecrets(),{apiKey:key,webhookSecret:webhook});const status=await settings.stripeSettingsStatus();assert.equal(status.configured,true);assert(!JSON.stringify(status).includes(key));assert(!JSON.stringify(status).includes(webhook));await assert.rejects(settings.saveStripeSecrets({apiKey:'sk_live_1234567890123456',webhookSecret:webhook},'owner'));}finally{if(previous===undefined)delete process.env.AI_SETTINGS_ENCRYPTION_KEY;else process.env.AI_SETTINGS_ENCRYPTION_KEY=previous;}});
test('test checkout is expired and provider errors never expose secrets',async()=>{const original=global.fetch,calls=[];global.fetch=async(url,options)=>{calls.push(String(url));let value={};if(String(url).includes('/prices/')){const pro=String(url).endsWith(policy.TEST_PRICES.pro);value={id:pro?policy.TEST_PRICES.pro:policy.TEST_PRICES.expert,livemode:false,active:true,currency:'eur',unit_amount:pro?2400:4900,recurring:{interval:'month',interval_count:1}};}else if(String(url).endsWith('/checkout/sessions'))value={id:'cs_test_123456789012',livemode:false};return Response.json(value);};try{await http.testStripeKey(key,'https://app.test');assert(calls.some(p=>p.endsWith('/cs_test_123456789012/expire')));global.fetch=async()=>Response.json({error:{message:key}},{status:401});await assert.rejects(http.testStripeKey(key,'https://app.test'),e=>e.code==='invalid_key'&&!e.message.includes(key));}finally{global.fetch=original;}});
test('live keys and corrupted storage cannot enable billing',async()=>{for(const value of [{apiKey:'sk_live_1234567890123456',webhookSecret:webhook},null]){const c=compile('lib/plan-billing-config.ts',{'./stripe-test-policy':policy,'./stripe-settings':{getStripeSecrets:async()=>{if(value===null)throw Error('storage');return value;}}});assert.deepEqual(await c.billingPublicStatus(),{ready:false,mode:'test'});}});

test('portal setup reuses its own configuration and isolates other sites',async()=>{const old=global.fetch;let writes=0;global.fetch=async(url,opts)=>{if(!opts.body)return Response.json({data:[{id:'bpc_other',livemode:false,metadata:{application:'cockpit-marches-ai',origin:'https://other.test',settings_version:'1'}}]});writes++;const b=opts.body;assert.equal(b.get('metadata[origin]'),'https://app.test');assert.equal(b.get('features[subscription_cancel][mode]'),'at_period_end');assert.equal(b.get('features[subscription_update][products][0][prices][0]'),policy.TEST_PRICES.pro);return Response.json({id:'bpc_test123',livemode:false});};try{assert.equal(await http.prepareStripePortal(key,'https://app.test'),'bpc_test123');assert.equal(writes,1);global.fetch=async()=>Response.json({data:[{id:'bpc_saved',livemode:false,metadata:{application:'cockpit-marches-ai',origin:'https://app.test',settings_version:'1'}}]});assert.equal(await http.prepareStripePortal(key,'https://app.test'),'bpc_saved');assert.equal(writes,1);}finally{global.fetch=old;}});

test('managed signing secret wins over saved webhook and is never exposed by status',async()=>{const previous=process.env.STRIPE_MANAGED_WEBHOOK_SECRET;process.env.STRIPE_MANAGED_WEBHOOK_SECRET='whsec_managed1234567890';try{const settings=compile('lib/stripe-settings.ts',{'./stripe-settings-store':{readStripeSettings:async()=>({encrypted_key:'cipher'}),writeStripeSettings:async()=>{}},'./stripe-secret-crypto':{openKey:async()=>JSON.stringify({apiKey:key,webhookSecret:webhook}),sealKey:async()=>''},'./stripe-test-policy':policy});const encryption=process.env.AI_SETTINGS_ENCRYPTION_KEY;process.env.AI_SETTINGS_ENCRYPTION_KEY='x'.repeat(32);try{assert.equal((await settings.getStripeSecrets()).webhookSecret,process.env.STRIPE_MANAGED_WEBHOOK_SECRET);const status=await settings.stripeSettingsStatus();assert.equal(status.managedWebhook,true);assert(!JSON.stringify(status).includes('whsec_'));}finally{if(encryption===undefined)delete process.env.AI_SETTINGS_ENCRYPTION_KEY;else process.env.AI_SETTINGS_ENCRYPTION_KEY=encryption;}}finally{if(previous===undefined)delete process.env.STRIPE_MANAGED_WEBHOOK_SECRET;else process.env.STRIPE_MANAGED_WEBHOOK_SECRET=previous;}});
