import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const indicatorEngine=fs.readFileSync('lib/indicator-engine.ts','utf8');
const indicatorRoute=fs.readFileSync('app/api/indicators/route.ts','utf8');
const ichimokuHistory=fs.readFileSync('lib/ichimoku-history.ts','utf8');
const ichimokuHistoryRoute=fs.readFileSync('app/api/ichimoku-history/route.ts','utf8');
const flutterIndicators=fs.readFileSync('mobile/lib/features/indicators/data/indicator_repository.dart','utf8');
const flutterHistory=fs.readFileSync('mobile/lib/features/history/data/history_repository.dart','utf8');
const flutterIchimoku=fs.readFileSync('mobile/lib/features/history/data/ichimoku_history_repository.dart','utf8');
const flutterMarketStatus=fs.readFileSync('mobile/lib/features/markets/data/market_status_repository.dart','utf8');
const flutterNewsAlerts=fs.readFileSync('mobile/lib/features/news/data/news_alert_repository.dart','utf8');
const flutterNewsPreferences=fs.readFileSync('mobile/lib/features/news/presentation/notification_preferences_view.dart','utf8');
const flutterPaperTrading=fs.readFileSync('mobile/lib/features/paper_trading/presentation/paper_trading_view.dart','utf8');
const flutterIdentity=fs.readFileSync('mobile/lib/features/auth/data/identity_repository.dart','utf8');
const flutterMobileSession=fs.readFileSync('mobile/lib/features/auth/data/mobile_session_repository.dart','utf8');
const flutterConnectionGate=fs.readFileSync('mobile/lib/features/auth/presentation/mobile_connection_gate.dart','utf8');
const flutterUserSync=fs.readFileSync('mobile/lib/features/sync/data/user_sync_repository.dart','utf8');
const flutterWatchlist=fs.readFileSync('mobile/lib/features/watchlist/presentation/watchlist_view.dart','utf8');
const flutterShell=fs.readFileSync('mobile/lib/app_shell.dart','utf8');
const manifest=fs.readFileSync('app/api/sync/manifest/route.ts','utf8');
const marketSessions=fs.readFileSync('lib/market-sessions.ts','utf8');
const marketStatusRoute=fs.readFileSync('app/api/market-status/route.ts','utf8');
const userIdentity=fs.readFileSync('lib/user-identity.ts','utf8');
const userSyncStore=fs.readFileSync('lib/user-sync-store.ts','utf8');
const userSyncSchema=fs.readFileSync('db/schema.ts','utf8');
const meRoute=fs.readFileSync('app/api/me/route.ts','utf8');
const mobileSessionRoute=fs.readFileSync('app/api/mobile-session/route.ts','utf8');
const userSyncCapabilitiesRoute=fs.readFileSync('app/api/user-sync/capabilities/route.ts','utf8');
const userSyncSnapshotRoute=fs.readFileSync('app/api/user-sync/snapshot/route.ts','utf8');
const userSyncWatchlistRoute=fs.readFileSync('app/api/user-sync/watchlist/route.ts','utf8');
const userSyncPreferencesRoute=fs.readFileSync('app/api/user-sync/notification-preferences/route.ts','utf8');
const userSyncReadsRoute=fs.readFileSync('app/api/user-sync/notification-reads/route.ts','utf8');
const paperTradesRoute=fs.readFileSync('app/api/user-sync/paper-trades/route.ts','utf8');
const webWatchlist=fs.readFileSync('app/watchlist/page.tsx','utf8');
const webJournal=fs.readFileSync('app/journal/page.tsx','utf8');
const newsSource=fs.readFileSync('lib/news-source.ts','utf8');
const newsAlertEngine=fs.readFileSync('lib/news-alert-engine.ts','utf8');
const newsRoute=fs.readFileSync('app/api/news/route.ts','utf8');
const newsAlertsRoute=fs.readFileSync('app/api/news-alerts/route.ts','utf8');
const webNotifications=fs.readFileSync('app/notifications/page.tsx','utf8');

test('indicator engine exposes every synchronized indicator',()=>{for(const name of ['Ichimoku Kinko Hyo','EMA 20 / EMA 50','RSI 14','MACD 12 / 26','Bandes de Bollinger','ATR 14','Supports / Résistances'])assert.match(indicatorEngine,new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('web indicator route delegates to shared engine',()=>{assert.match(indicatorRoute,/buildIndicatorCenter/);assert.match(indicatorRoute,/history\(/);assert.match(indicatorRoute,/timeframeSnapshot/);});
test('flutter consumes the web indicator contract',()=>{assert.match(flutterIndicators,/\/api\/indicators/);assert.match(flutterIndicators,/consensus/);assert.doesNotMatch(flutterIndicators,/tenkan|kijun|bollingerUpper|ema\(/i);});
test('flutter consumes shared history and timeframe contracts',()=>{assert.match(flutterHistory,/\/api\/history/);assert.match(flutterHistory,/compare=1/);assert.match(flutterHistory,/TimeframeComparison/);});
test('Ichimoku historical entries and exits are centralized',()=>{assert.match(ichimokuHistory,/buildIchimokuHistoricalSignals/);assert.match(ichimokuHistory,/ACHETER/);assert.match(ichimokuHistory,/VENDRE/);assert.match(ichimokuHistoryRoute,/buildIchimokuHistoricalSignals/);assert.match(flutterIchimoku,/\/api\/ichimoku-history/);assert.doesNotMatch(flutterIchimoku,/midpoint|tenkan|kijun/i);assert.match(flutterShell,/PriceSparkline/);});
test('market sessions are centralized and consumed by Flutter',()=>{assert.match(marketSessions,/BEL20/);assert.match(marketSessions,/indexMarketStatus/);assert.match(marketStatusRoute,/indexMarketStatus/);assert.match(flutterMarketStatus,/\/api\/market-status/);assert.doesNotMatch(flutterMarketStatus,/America\/New_York|Europe\/Brussels|Asia\/Tokyo/);});
test('news source and alert classification are centralized',()=>{assert.match(newsRoute,/loadNewsByAsset/);assert.match(newsAlertsRoute,/loadNewsByAsset/);assert.match(newsAlertsRoute,/buildNewsAlerts/);assert.match(newsAlertEngine,/CRITIQUE/);assert.match(newsAlertEngine,/IMPORTANT/);assert.match(newsSource,/newsForAsset/);assert.match(flutterNewsAlerts,/\/api\/news-alerts/);assert.match(flutterShell,/NewsAlertsView/);assert.match(webNotifications,/\/api\/news-alerts/);});
test('identity contract supports signed mobile sessions without invented ids',()=>{assert.match(userIdentity,/oai-authenticated-user-email/);assert.match(userIdentity,/MOBILE_SESSION_SECRET/);assert.match(userIdentity,/HMAC/);assert.match(meRoute,/getSharedUserIdentity/);assert.match(mobileSessionRoute,/createMobileSessionToken/);assert.match(flutterIdentity,/\/api\/me/);assert.match(flutterMobileSession,/flutter_secure_storage/);assert.match(flutterConnectionGate,/\/api\/me/);assert.doesNotMatch(flutterIdentity,/random|uuid|deviceId/i);});
test('durable user domains use direct Vercel Neon storage and never local fallbacks',()=>{for(const table of ['user_profiles','watchlist_items','notification_preferences','notification_reads','notification_devices','paper_trades'])assert.match(userSyncSchema,new RegExp(table));assert.match(userSyncStore,/@neondatabase\/serverless/);assert.match(userSyncStore,/DATABASE_URL|POSTGRES_URL|NEON_DATABASE_URL|NEON_POSTGRES_URL/);assert.doesNotMatch(userSyncStore,/USER_SYNC_API_URL|USER_SYNC_API_SECRET|new Map|localStorage|sessionStorage/);assert.match(userSyncCapabilitiesRoute,/userSyncStoreConfigured/);assert.match(userSyncSnapshotRoute,/getSnapshot/);assert.match(userSyncWatchlistRoute,/setWatchlist/);assert.match(userSyncPreferencesRoute,/setNotificationPreferences/);assert.match(userSyncReadsRoute,/markNotificationsRead/);assert.match(flutterUserSync,/\/api\/user-sync\/snapshot/);assert.match(flutterUserSync,/\/api\/user-sync\/watchlist/);});
test('watchlist is synchronized through server APIs on web and Flutter',()=>{assert.match(webWatchlist,/\/api\/user-sync\/snapshot/);assert.match(webWatchlist,/\/api\/user-sync\/watchlist/);assert.match(flutterWatchlist,/setWatchlist/);assert.match(flutterWatchlist,/snapshot/);assert.match(flutterShell,/WatchlistView/);assert.match(flutterShell,/label:'Favoris'/);assert.doesNotMatch(webWatchlist,/localStorage|sessionStorage/);assert.doesNotMatch(flutterWatchlist,/SharedPreferences|Hive|Isar/);});
test('notification read state is synchronized on web and Flutter',()=>{assert.match(webNotifications,/\/api\/user-sync\/snapshot/);assert.match(webNotifications,/\/api\/user-sync\/notification-reads/);assert.match(flutterShell,/markNotificationsRead/);assert.match(flutterShell,/readNotificationIds/);assert.doesNotMatch(webNotifications,/localStorage|sessionStorage/);});
test('notification preferences are synchronized on web and Flutter',()=>{assert.match(webNotifications,/\/api\/user-sync\/notification-preferences/);assert.match(webNotifications,/minimumSeverity/);assert.match(webNotifications,/watchedOnly/);assert.match(webNotifications,/pushEnabled/);assert.match(webNotifications,/resolvedOptions\(\)\.timeZone/);assert.match(flutterNewsPreferences,/setNotificationPreferences/);assert.match(flutterNewsPreferences,/quietHoursStart/);assert.match(flutterNewsPreferences,/quietHoursEnd/);assert.match(flutterUserSync,/utcOffsetMinutes/);assert.match(flutterShell,/NotificationPreferencesView/);});
test('paper trading journal is synchronized and simulation only',()=>{assert.match(paperTradesRoute,/listPaperTrades/);assert.match(paperTradesRoute,/createPaperTrade/);assert.match(paperTradesRoute,/closePaperTrade/);assert.match(paperTradesRoute,/deletePaperTrade/);assert.match(userSyncStore,/paper_trades/);assert.match(flutterUserSync,/\/api\/user-sync\/paper-trades/);assert.match(flutterPaperTrading,/Simulation uniquement/);assert.match(flutterShell,/PaperTradingView/);assert.match(flutterShell,/label:'Journal'/);assert.match(webJournal,/\/api\/user-sync\/paper-trades/);assert.match(webJournal,/aucun ordre réel exécuté/);});
test('sync manifest publishes contract version and endpoints',()=>{assert.match(manifest,/schemaVersion:'2\.1\.0'/);for(const endpoint of ['/api/me','/api/mobile-session','/api/user-sync/capabilities','/api/user-sync/snapshot','/api/user-sync/watchlist','/api/user-sync/notification-preferences','/api/user-sync/notification-reads','/api/user-sync/notification-devices','/api/user-sync/paper-trades','/api/notifications/personalized','/api/notifications/dispatch-preview','/api/scanner','/api/history','/api/indicators','/api/ichimoku-history','/api/market-status','/api/news','/api/news-alerts'])assert.match(manifest,new RegExp(endpoint.replaceAll('/','\\/')));});
