import{verifyStripeWebhook}from'@/lib/stripe-rest';
import{findUserIdByStripeCustomer,findUserIdByStripeSubscription,getBillingState,markWebhookEventProcessed,upsertBillingState,webhookEventProcessed}from'@/lib/billing-store';
import{planFromPriceId}from'@/lib/billing-config';

export const runtime='nodejs';

type StripeEvent={id:string;type:string;data:{object:any}};

async function resolveUserId(object:any){return String(object?.metadata?.user_id||'')||await findUserIdByStripeSubscription(String(object?.id||''))||await findUserIdByStripeCustomer(String(object?.customer||''));}

async function applySubscription(object:any){const userId=await resolveUserId(object);if(!userId)return;const state=await getBillingState(userId);const priceId=object?.items?.data?.[0]?.price?.id?String(object.items.data[0].price.id):state.stripePriceId;const status=String(object?.status||state.status) as any;await upsertBillingState({...state,userId,plan:status==='canceled'? 'FREE':planFromPriceId(priceId),status:status==='canceled'?'canceled':status,stripeCustomerId:object?.customer?String(object.customer):state.stripeCustomerId,stripeSubscriptionId:object?.id?String(object.id):state.stripeSubscriptionId,stripePriceId:priceId,currentPeriodEnd:object?.current_period_end?Number(object.current_period_end)*1000:state.currentPeriodEnd,cancelAtPeriodEnd:Boolean(object?.cancel_at_period_end),updatedAt:Date.now()});}

export async function POST(req:Request){const raw=await req.text();if(!verifyStripeWebhook(raw,req.headers.get('stripe-signature')))return Response.json({error:'invalid_signature'},{status:400});let event:StripeEvent;try{event=JSON.parse(raw);}catch{return Response.json({error:'invalid_json'},{status:400});}try{if(await webhookEventProcessed(event.id))return Response.json({ok:true,duplicate:true});const object=event.data?.object;if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type))await applySubscription(object);if(event.type==='checkout.session.completed'){const userId=String(object?.client_reference_id||object?.metadata?.user_id||'');if(userId){const state=await getBillingState(userId);await upsertBillingState({...state,stripeCustomerId:object?.customer?String(object.customer):state.stripeCustomerId,stripeSubscriptionId:object?.subscription?String(object.subscription):state.stripeSubscriptionId,updatedAt:Date.now()});}}if(event.type==='invoice.payment_failed'){const userId=await findUserIdByStripeCustomer(String(object?.customer||''));if(userId){const state=await getBillingState(userId);await upsertBillingState({...state,status:'past_due',updatedAt:Date.now()});}}await markWebhookEventProcessed(event.id,event.type);return Response.json({ok:true});}catch(e){return Response.json({error:e instanceof Error?e.message:'webhook_failed'},{status:500});}}
