import{assets}from'@/lib/market-data';
import{authorizeFeatureApi}from'@/lib/access-control';
import{getUserSyncStore,userSyncStoreConfigured,type PaperTradeSide}from'@/lib/user-sync-store';

const validAssets=new Set<string>(assets.map(a=>a.key));
const validSides=new Set<PaperTradeSide>(['BUY','SELL']);
function positiveDecimal(value:unknown){if(typeof value!=='string'&&typeof value!=='number')return null;const text=String(value).trim();const n=Number(text);return Number.isFinite(n)&&n>0?text:null;}
async function user(){const auth=await authorizeFeatureApi('PAPER_TRADING');if(auth.response)return{error:auth.response};if(!userSyncStoreConfigured())return{error:Response.json({error:'storage_not_configured'},{status:503})};return{identity:auth.context.identity};}

export async function GET(){const auth=await user();if(auth.error)return auth.error;try{const trades=await getUserSyncStore().listPaperTrades(auth.identity!.id);return Response.json({trades},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'storage_unavailable'},{status:503});}}

export async function POST(req:Request){const auth=await user();if(auth.error)return auth.error;let body:any;try{body=await req.json()}catch{return Response.json({error:'invalid_json'},{status:400})}const assetKey=typeof body?.assetKey==='string'?body.assetKey:'';const side=typeof body?.side==='string'?body.side.toUpperCase() as PaperTradeSide:null;const quantity=positiveDecimal(body?.quantity),entryPrice=positiveDecimal(body?.entryPrice);const note=typeof body?.note==='string'&&body.note.trim()?body.note.trim().slice(0,2000):null;if(!validAssets.has(assetKey))return Response.json({error:'invalid_asset'},{status:400});if(!side||!validSides.has(side))return Response.json({error:'invalid_side'},{status:400});if(!quantity||!entryPrice)return Response.json({error:'invalid_quantity_or_price'},{status:400});try{const trade=await getUserSyncStore().createPaperTrade(auth.identity!.id,{id:crypto.randomUUID(),assetKey,side,quantity,entryPrice,openedAt:Date.now(),note});return Response.json({ok:true,trade},{status:201,headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'storage_unavailable'},{status:503});}}

export async function PATCH(req:Request){const auth=await user();if(auth.error)return auth.error;let body:any;try{body=await req.json()}catch{return Response.json({error:'invalid_json'},{status:400})}const id=typeof body?.id==='string'?body.id:'';const exitPrice=positiveDecimal(body?.exitPrice);if(!id||!exitPrice)return Response.json({error:'id_and_exitPrice_required'},{status:400});try{const trade=await getUserSyncStore().closePaperTrade(auth.identity!.id,id,exitPrice,Date.now());if(!trade)return Response.json({error:'trade_not_found_or_closed'},{status:404});return Response.json({ok:true,trade},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'storage_unavailable'},{status:503});}}

export async function DELETE(req:Request){const auth=await user();if(auth.error)return auth.error;const id=new URL(req.url).searchParams.get('id')||'';if(!id)return Response.json({error:'id_required'},{status:400});try{const deleted=await getUserSyncStore().deletePaperTrade(auth.identity!.id,id);if(!deleted)return Response.json({error:'trade_not_found'},{status:404});return Response.json({ok:true},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'storage_unavailable'},{status:503});}}
