"use client";
import {useState} from 'react';
import {useLanguage} from '@/lib/use-language';
const copies={
 fr:{title:'Mon compte',name:'Nom affiché',save:'Enregistrer',saving:'Enregistrement…',saved:'Profil enregistré.',error:'Enregistrement impossible. Vos modifications sont conservées : réessayez.',subscription:'Mon abonnement',portal:'Gérer mon abonnement',offers:'Voir les offres',test:'Paiements en mode test — aucun débit réel.',unavailable:'Le portail de paiement est indisponible pour ce compte.',renew:'Prochaine échéance',end:'Fin prévue de l’abonnement',free:'Découverte',active:'Actif',trialing:'Essai',past_due:'Paiement en attente',canceled:'Résilié',suspended:'Suspendu',inactive:'Sans abonnement Stripe'},
 en:{title:'My account',name:'Display name',save:'Save',saving:'Saving…',saved:'Profile saved.',error:'Unable to save. Your changes are preserved; please retry.',subscription:'My subscription',portal:'Manage subscription',offers:'View plans',test:'Test payments — no real charge.',unavailable:'The payment portal is unavailable for this account.',renew:'Next billing date',end:'Scheduled subscription end',free:'Discovery',active:'Active',trialing:'Trial',past_due:'Payment pending',canceled:'Canceled',suspended:'Suspended',inactive:'No Stripe subscription'},
 de:{title:'Mein Konto',name:'Anzeigename',save:'Speichern',saving:'Wird gespeichert…',saved:'Profil gespeichert.',error:'Speichern fehlgeschlagen. Ihre Änderungen bleiben erhalten; bitte erneut versuchen.',subscription:'Mein Abonnement',portal:'Abonnement verwalten',offers:'Tarife ansehen',test:'Testzahlungen — keine echte Abbuchung.',unavailable:'Das Zahlungsportal ist für dieses Konto nicht verfügbar.',renew:'Nächster Zahlungstermin',end:'Geplantes Abonnementende',free:'Entdecken',active:'Aktiv',trialing:'Testphase',past_due:'Zahlung ausstehend',canceled:'Gekündigt',suspended:'Gesperrt',inactive:'Kein Stripe-Abonnement'},
 nl:{title:'Mijn account',name:'Weergavenaam',save:'Opslaan',saving:'Opslaan…',saved:'Profiel opgeslagen.',error:'Opslaan mislukt. Uw wijzigingen blijven behouden; probeer opnieuw.',subscription:'Mijn abonnement',portal:'Abonnement beheren',offers:'Bekijk abonnementen',test:'Testbetalingen — geen echte afschrijving.',unavailable:'Het betaalportaal is niet beschikbaar voor dit account.',renew:'Volgende betaaldatum',end:'Gepland einde abonnement',free:'Ontdekken',active:'Actief',trialing:'Proefperiode',past_due:'Betaling in afwachting',canceled:'Opgezegd',suspended:'Geblokkeerd',inactive:'Geen Stripe-abonnement'}
};
export default function AccountDetails({email,displayName,plan,status,portalAvailable,editable=false,periodEnd,cancelAtEnd=false}:{email:string;displayName:string;plan:string;status:string;portalAvailable:boolean;editable?:boolean;periodEnd?:number|null;cancelAtEnd?:boolean}){
 const [lang]=useLanguage(),c=copies[lang];const[name,setName]=useState(displayName),[state,setState]=useState('idle');
 async function save(e:React.FormEvent){e.preventDefault();if(state==='saving')return;setState('saving');try{const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({displayName:name})});setState(r.ok?'saved':'error');}catch{setState('error');}}
 const normalized=status.toLowerCase();const label=c[normalized as keyof typeof c]||status;
 return <section style={{border:'1px solid #284450',borderRadius:18,padding:24,margin:'24px 0',background:'#0b1928',color:'#ecf6f5'}}>
 <h1>{c.title}</h1><p>{email}</p>
 {editable?<form onSubmit={save}><label>{c.name}<input style={{display:'block',padding:10,margin:'8px 0',maxWidth:'100%',color:'#ecf6f5',background:'#122635',border:'1px solid #52717a',borderRadius:8}} required minLength={2} maxLength={80} value={name} disabled={state==='saving'} onChange={e=>{setName(e.target.value);setState('idle');}}/></label><button disabled={state==='saving'}>{state==='saving'?c.saving:c.save}</button>{state==='saved'&&<p role="status">{c.saved}</p>}{state==='error'&&<p role="alert">{c.error}</p>}</form>:<p>{displayName}</p>}
 <h2>{c.subscription}</h2><p>{['free','DISCOVERY'].includes(plan)?c.free:plan.toLowerCase()==='pro'?'Pro':'Expert / Trader+'} · {label}</p>
 {periodEnd!=null&&Number.isFinite(periodEnd)&&<p>{cancelAtEnd?c.end:c.renew} : {new Date(periodEnd).toLocaleDateString(lang,{timeZone:'UTC'})} (UTC)</p>}
 <p>{c.test}</p>{portalAvailable?<form action="/api/billing/portal" method="post"><button type="submit">{c.portal}</button></form>:<p>{c.unavailable}</p>}<a href="/pricing">{c.offers}</a>
 </section>;
}
