"use client";
import {useState} from 'react';
import {ArrowUpRight,Check,ShieldCheck,UserRound,Sparkles,FlaskConical,Save,Mail} from 'lucide-react';
import './account-details.css';
import {useLanguage} from '@/lib/use-language';
const copies={
 fr:{title:'Mon compte',name:'Nom affiché',save:'Enregistrer',saving:'Enregistrement…',saved:'Profil enregistré.',error:'Enregistrement impossible. Vos modifications sont conservées : réessayez.',subscription:'Mon abonnement',portal:'Gérer mon abonnement',offers:'Voir les offres',test:'Paiements en mode test — aucun débit réel.',unavailable:'Le portail de paiement est indisponible pour ce compte.',renew:'Prochaine échéance',end:'Fin prévue de l’abonnement',free:'Découverte',active:'Actif',trialing:'Essai',past_due:'Paiement en attente',canceled:'Résilié',suspended:'Suspendu',inactive:'Sans abonnement Stripe'},
 en:{title:'My account',name:'Display name',save:'Save',saving:'Saving…',saved:'Profile saved.',error:'Unable to save. Your changes are preserved; please retry.',subscription:'My subscription',portal:'Manage subscription',offers:'View plans',test:'Test payments — no real charge.',unavailable:'The payment portal is unavailable for this account.',renew:'Next billing date',end:'Scheduled subscription end',free:'Discovery',active:'Active',trialing:'Trial',past_due:'Payment pending',canceled:'Canceled',suspended:'Suspended',inactive:'No Stripe subscription'},
 de:{title:'Mein Konto',name:'Anzeigename',save:'Speichern',saving:'Wird gespeichert…',saved:'Profil gespeichert.',error:'Speichern fehlgeschlagen. Ihre Änderungen bleiben erhalten; bitte erneut versuchen.',subscription:'Mein Abonnement',portal:'Abonnement verwalten',offers:'Tarife ansehen',test:'Testzahlungen — keine echte Abbuchung.',unavailable:'Das Zahlungsportal ist für dieses Konto nicht verfügbar.',renew:'Nächster Zahlungstermin',end:'Geplantes Abonnementende',free:'Entdecken',active:'Aktiv',trialing:'Testphase',past_due:'Zahlung ausstehend',canceled:'Gekündigt',suspended:'Gesperrt',inactive:'Kein Stripe-Abonnement'},
 nl:{title:'Mijn account',name:'Weergavenaam',save:'Opslaan',saving:'Opslaan…',saved:'Profiel opgeslagen.',error:'Opslaan mislukt. Uw wijzigingen blijven behouden; probeer opnieuw.',subscription:'Mijn abonnement',portal:'Abonnement beheren',offers:'Bekijk abonnementen',test:'Testbetalingen — geen echte afschrijving.',unavailable:'Het betaalportaal is niet beschikbaar voor dit account.',renew:'Volgende betaaldatum',end:'Gepland einde abonnement',free:'Ontdekken',active:'Actief',trialing:'Proefperiode',past_due:'Betaling in afwachting',canceled:'Opgezegd',suspended:'Geblokkeerd',inactive:'Geen Stripe-abonnement'}
};
export default function AccountDetails({email,displayName,plan,status,portalAvailable,editable=false,periodEnd,cancelAtEnd=false}:{email:string;displayName:string;plan:string;status:string;portalAvailable:boolean;editable?:boolean;periodEnd?:number|null;cancelAtEnd?:boolean}){
 const [lang]=useLanguage(),c=copies[lang];const[name,setName]=useState(displayName),[state,setState]=useState('idle');
 async function save(e:React.FormEvent){e.preventDefault();if(state==='saving')return;setState('saving');try{const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({displayName:name})});setState(r.ok?'saved':'error');}catch{setState('error');}}
 const normalized=status.toLowerCase();const label=c[normalized as keyof typeof c]||status;
 const planName=['free','DISCOVERY'].includes(plan)?c.free:plan.toLowerCase()==='pro'?'Pro':'Expert / Trader+';
 const extra={fr:['Votre espace personnel','Tout votre cockpit, à votre rythme.','Profil personnel','Vos informations de connexion','Votre formule','Accéder au cockpit','Votre identité reste associée à votre compte sécurisé.','Modifier mon profil'],en:['Your personal space','Your cockpit, at your own pace.','Personal profile','Your sign-in information','Your plan','Open cockpit','Your identity stays linked to your secure account.','Edit my profile'],de:['Ihr persönlicher Bereich','Ihr Cockpit, in Ihrem Tempo.','Persönliches Profil','Ihre Anmeldeinformationen','Ihr Tarif','Cockpit öffnen','Ihre Identität bleibt mit Ihrem sicheren Konto verknüpft.','Profil bearbeiten'],nl:['Uw persoonlijke ruimte','Uw cockpit, op uw tempo.','Persoonlijk profiel','Uw inloggegevens','Uw pakket','Cockpit openen','Uw identiteit blijft gekoppeld aan uw beveiligde account.','Profiel bewerken']}[lang];
 return <section className="member-space">
 <div className="member-hero"><div className="member-orbits" aria-hidden="true"><span/><span/><Sparkles/></div><div className="member-hero-content"><p className="member-eyebrow"><span/> {extra[0]}</p><h1>{c.title}<span>.</span></h1><p className="member-intro">{extra[1]}</p><div className="member-identity"><div className="member-avatar">{displayName.trim().slice(0,1).toUpperCase()||'•'}</div><div><strong>{displayName}</strong><span>{email}</span></div></div></div><a className="member-button member-primary" href="/">{extra[5]}<ArrowUpRight size={18}/></a></div>
 <div className="member-grid"><section className="member-card"><div className="member-card-heading"><span className="member-icon"><UserRound size={21}/></span><div><h2>{extra[2]}</h2><p>{extra[3]}</p></div></div>
 {editable?<form className="member-form" onSubmit={save}><label>{c.name}<input required minLength={2} maxLength={80} value={name} disabled={state==='saving'} onChange={e=>{setName(e.target.value);setState('idle');}}/></label><label>{c.title==='My account'?'Email':'E-mail'}<span className="member-email"><Mail size={16}/>{email}</span></label><button className="member-button member-primary" disabled={state==='saving'}><Save size={17}/>{state==='saving'?c.saving:c.save}</button>{state==='saved'&&<p className="member-success" role="status"><Check size={16}/>{c.saved}</p>}{state==='error'&&<p className="member-error" role="alert">{c.error}</p>}</form>:<div className="member-profile"><strong>{displayName}</strong><p>{email}</p><a className="member-button member-secondary" href="/account/profile">{extra[7]}<ArrowUpRight size={17}/></a></div>}
 <p className="member-security"><ShieldCheck size={16}/>{extra[6]}</p></section>
 <section className="member-card member-plan"><div className="member-card-heading"><span className="member-icon"><Sparkles size={21}/></span><div><h2>{c.subscription}</h2><p>{extra[4]}</p></div><span className={'member-status '+(['active','trialing'].includes(normalized)?'is-active':'')}><span/>{label}</span></div><div className="member-plan-name">{planName}</div><div className="member-plan-line"/>
 {periodEnd!=null&&Number.isFinite(periodEnd)&&<p className="member-period">{cancelAtEnd?c.end:c.renew}<strong>{new Date(periodEnd).toLocaleDateString(lang,{timeZone:'UTC'})} (UTC)</strong></p>}
 <p className="member-test"><FlaskConical size={17}/>{c.test}</p>{portalAvailable?<form action="/api/billing/portal" method="post"><button className="member-button member-primary" type="submit">{c.portal}<ArrowUpRight size={18}/></button></form>:<p className="member-muted">{c.unavailable}</p>}<a className="member-button member-secondary" href="/pricing">{c.offers}<ArrowUpRight size={18}/></a>
 </section></div></section>;
}
