"use client";
import {useEffect,useState,useId} from 'react';
import {useLanguage} from '@/lib/use-language';
import {Sparkles,ShieldCheck} from 'lucide-react';
import './ai-allowance.css';
type Allowance={used:number;limit:number|null;remaining:number|null;resetAt:number;automaticAllowed:boolean};
const copy={fr:['analyses IA disponibles','Accès administrateur','Renouvellement le','Quota utilisé. Vous pouvez continuer à utiliser les autres fonctions du cockpit.','Voir les packs','Analyse automatique (consomme votre quota)','Les analyses en échec ne sont pas décomptées.','Connectez-vous pour bénéficier de 5 analyses IA gratuites par mois.'],en:['AI analyses available','Administrator access','Renews on','Quota used. Other cockpit features remain available.','View plans','Automatic analysis (uses your quota)','Failed analyses do not use your quota.','Sign in for 5 free AI analyses each month.'],de:['KI-Analysen verfügbar','Administratorzugang','Erneuerung am','Kontingent verbraucht. Andere Cockpit-Funktionen bleiben verfügbar.','Tarife ansehen','Automatische Analyse (verbraucht Kontingent)','Fehlgeschlagene Analysen werden nicht gezählt.','Anmelden für 5 kostenlose KI-Analysen pro Monat.'],nl:['AI-analyses beschikbaar','Beheerderstoegang','Vernieuwd op','Limiet bereikt. Andere cockpitfuncties blijven beschikbaar.','Pakketten bekijken','Automatische analyse (gebruikt uw tegoed)','Mislukte analyses tellen niet mee.','Log in voor 5 gratis AI-analyses per maand.']}as const;

const automaticCopy={
 fr:['Analyse automatique','L’IA suit votre sélection','Mode manuel','Mode automatique activé','Dans Cockpit et Prévisions, l’IA peut relancer une analyse lorsque l’actif, la période, la langue ou les données changent, dès que les données sont prêtes.','Choisissez un actif','L’IA analyse','Consultez son éclairage','Chaque nouvelle analyse réussie utilise un crédit. Les actualisations peuvent donc consommer plusieurs crédits.','Accès administrateur : analyses sans quota.','Désactivé : vous choisissez quand lancer l’analyse avec le bouton dédié.','Activé : les prochaines analyses peuvent démarrer sans clic. Vous pouvez désactiver ce mode à tout moment.','L’IA vous éclaire ; vous gardez la décision. Aucun ordre n’est passé.','Quota épuisé : le mode automatique est arrêté.','Activer ou désactiver l’analyse automatique'],
 en:['Automatic analysis','AI follows your selection','Manual mode','Automatic mode enabled','In Cockpit and Forecasts, AI can run a new analysis when the asset, timeframe, language or data changes, once the data is ready.','Choose an asset','AI analyses','Read its insights','Each successful new analysis uses one credit. Data updates may therefore use several credits.','Administrator access: no analysis quota.','Off: choose when to run an analysis using the dedicated button.','On: new analyses may start without a click. You can turn this mode off at any time.','AI provides insights; you decide. No orders are placed.','Quota exhausted: automatic mode has stopped.','Toggle automatic analysis'],
 de:['Automatische Analyse','KI folgt Ihrer Auswahl','Manueller Modus','Automatik aktiviert','Im Cockpit und in Prognosen kann die KI bei Änderungen von Anlage, Zeitraum, Sprache oder Daten eine neue Analyse starten, sobald die Daten bereit sind.','Anlage wählen','KI analysiert','Erkenntnisse lesen','Jede erfolgreiche neue Analyse verbraucht ein Guthaben. Datenaktualisierungen können mehrere Guthaben verbrauchen.','Administratorzugang: Analysen ohne Kontingent.','Aus: Starten Sie Analysen selbst über die entsprechende Schaltfläche.','Ein: Neue Analysen können ohne Klick starten. Sie können diesen Modus jederzeit ausschalten.','KI unterstützt Sie; Sie entscheiden. Es werden keine Aufträge erteilt.','Kontingent aufgebraucht: Automatik gestoppt.','Automatische Analyse umschalten'],
 nl:['Automatische analyse','AI volgt uw selectie','Handmatige modus','Automatische modus actief','In Cockpit en Voorspellingen kan AI een nieuwe analyse starten wanneer het activum, de periode, taal of gegevens wijzigen, zodra de gegevens klaar zijn.','Kies een activum','AI analyseert','Lees de inzichten','Elke geslaagde nieuwe analyse gebruikt één krediet. Gegevensupdates kunnen dus meerdere kredieten gebruiken.','Beheerderstoegang: analyses zonder limiet.','Uit: start zelf een analyse met de daarvoor bestemde knop.','Aan: nieuwe analyses kunnen zonder klik starten. U kunt deze modus altijd uitschakelen.','AI ondersteunt u; u beslist. Er worden geen orders geplaatst.','Limiet bereikt: automatische modus gestopt.','Automatische analyse omschakelen']
} as const;

export default function AIAllowance({onAutomaticChange,onExhaustedChange}:{onAutomaticChange?:(value:boolean)=>void;onExhaustedChange?:(value:boolean)=>void}){const titleId=useId(),descriptionId=useId();const [lang]=useLanguage(),c=copy[lang],a=automaticCopy[lang],[data,setData]=useState<Allowance|null>(null),[anonymous,setAnonymous]=useState(false),[automatic,setAutomatic]=useState(false);
 useEffect(()=>{let alive=true;async function load(){try{const r=await fetch('/api/ai-allowance',{cache:'no-store'});if(!alive)return;if(r.status===401){setAnonymous(true);return;}if(!r.ok)return;const d=await r.json();if(!alive)return;setData(d);setAnonymous(false);onExhaustedChange?.(d.remaining===0);if(!d.automaticAllowed||d.remaining===0){setAutomatic(false);onAutomaticChange?.(false);}}catch{}}void load();window.addEventListener('ai-usage-changed',load);window.addEventListener('focus',load);return()=>{alive=false;window.removeEventListener('ai-usage-changed',load);window.removeEventListener('focus',load);};},[onAutomaticChange,onExhaustedChange]);
 return <div className="ai-allowance">{anonymous?<a href="/account">{c[7]}</a>:data&&<>
 <div className="ai-allowance-summary"><Sparkles size={17} aria-hidden="true"/><b>{data.limit===null?c[1]:`${data.remaining} / ${data.limit} ${c[0]}`}</b></div>
 {data.limit!==null&&<p className="ai-allowance-renew">{c[2]} {new Date(data.resetAt).toLocaleDateString(lang,{timeZone:'UTC'})} · <a href="/pricing">{c[4]}</a></p>}
 {data.remaining===0&&<p role="status">{c[3]}</p>}
 {data.automaticAllowed&&onAutomaticChange&&<section className={'ai-auto-card '+(automatic?'is-on':'')} aria-labelledby={titleId}>
 <div className="ai-auto-heading"><span className="ai-auto-symbol"><Sparkles aria-hidden="true"/></span><div><small>{a[1]}</small><h3 id={titleId}>{a[0]}</h3></div><button type="button" className="ai-auto-switch" role="switch" aria-checked={automatic} aria-label={a[14]} aria-describedby={descriptionId} disabled={data.remaining===0} onClick={()=>{const next=!automatic;setAutomatic(next);onAutomaticChange(next);}}><span/></button></div>
 <p id={descriptionId} className="ai-auto-description">{a[4]}</p>
 <ol className="ai-auto-steps">{[a[5],a[6],a[7]].map((step,index)=><li key={step}><span>{index+1}</span>{step}</li>)}</ol>
 <div className="ai-auto-state"><span className="ai-auto-dot" aria-hidden="true"/><strong>{automatic?a[3]:a[2]}</strong></div>
 <p className="ai-auto-help">{data.remaining===0?a[13]:automatic?a[11]:a[10]}</p>
 <div className="ai-auto-cost"><ShieldCheck size={18} aria-hidden="true"/><p>{data.limit===null?a[9]:a[8]}</p></div>
 <p className="ai-auto-disclaimer">{a[12]}</p>
 </section>}
 <p className="ai-allowance-note">{c[6]}</p></>}</div>;
}
