"use client";
import {useEffect,useState} from 'react';
import {useLanguage} from '@/lib/use-language';
type Allowance={used:number;limit:number|null;remaining:number|null;resetAt:number;automaticAllowed:boolean};
const copy={fr:['analyses IA disponibles','Accès administrateur','Renouvellement le','Quota utilisé. Vous pouvez continuer à utiliser les autres fonctions du cockpit.','Voir les packs','Analyse automatique (consomme votre quota)','Les analyses en échec ne sont pas décomptées.','Connectez-vous pour bénéficier de 5 analyses IA gratuites par mois.'],en:['AI analyses available','Administrator access','Renews on','Quota used. Other cockpit features remain available.','View plans','Automatic analysis (uses your quota)','Failed analyses do not use your quota.','Sign in for 5 free AI analyses each month.'],de:['KI-Analysen verfügbar','Administratorzugang','Erneuerung am','Kontingent verbraucht. Andere Cockpit-Funktionen bleiben verfügbar.','Tarife ansehen','Automatische Analyse (verbraucht Kontingent)','Fehlgeschlagene Analysen werden nicht gezählt.','Anmelden für 5 kostenlose KI-Analysen pro Monat.'],nl:['AI-analyses beschikbaar','Beheerderstoegang','Vernieuwd op','Limiet bereikt. Andere cockpitfuncties blijven beschikbaar.','Pakketten bekijken','Automatische analyse (gebruikt uw tegoed)','Mislukte analyses tellen niet mee.','Log in voor 5 gratis AI-analyses per maand.']}as const;
export default function AIAllowance({onAutomaticChange,onExhaustedChange}:{onAutomaticChange?:(value:boolean)=>void;onExhaustedChange?:(value:boolean)=>void}){const [lang]=useLanguage(),c=copy[lang],[data,setData]=useState<Allowance|null>(null),[anonymous,setAnonymous]=useState(false),[automatic,setAutomatic]=useState(false);
 useEffect(()=>{let alive=true;async function load(){try{const r=await fetch('/api/ai-allowance',{cache:'no-store'});if(!alive)return;if(r.status===401){setAnonymous(true);return;}if(!r.ok)return;const d=await r.json();if(!alive)return;setData(d);setAnonymous(false);onExhaustedChange?.(d.remaining===0);if(!d.automaticAllowed||d.remaining===0){setAutomatic(false);onAutomaticChange?.(false);}}catch{}}void load();window.addEventListener('ai-usage-changed',load);window.addEventListener('focus',load);return()=>{alive=false;window.removeEventListener('ai-usage-changed',load);window.removeEventListener('focus',load);};},[onAutomaticChange,onExhaustedChange]);
 return <div style={{padding:'14px 0',fontSize:14,borderTop:'1px solid #29404c',lineHeight:1.7}}>{anonymous?<a href="/account">{c[7]}</a>:data&&<><b>{data.limit===null?c[1]:`${data.remaining} / ${data.limit} ${c[0]}`}</b>{data.limit!==null&&<p>{c[2]} {new Date(data.resetAt).toLocaleDateString(lang,{timeZone:'UTC'})} · <a href="/pricing">{c[4]}</a></p>}{data.remaining===0&&<p role="status">{c[3]}</p>}{data.automaticAllowed&&onAutomaticChange&&<label><input type="checkbox" checked={automatic} onChange={e=>{setAutomatic(e.target.checked);onAutomaticChange(e.target.checked);}} disabled={data.remaining===0}/> {c[5]}</label>}<p style={{color:'#9fb6c3'}}>{c[6]}</p></>}</div>;
}
