"use client";
import {useEffect,useState} from 'react';
import {useLanguage} from '@/lib/use-language';
import './ai-settings.css';
const copy={fr:['Configuration IA','Administration','Clé OpenAI','Modèle OpenAI','Tester la connexion','Enregistrer','Clé configurée','Aucune clé configurée','Clé enregistrée : laissez ce champ vide pour la conserver.','La clé est chiffrée côté serveur et ne sera jamais réaffichée. Chaque test et enregistrement lance une courte requête OpenAI facturable.','Connexion réussie.','Configuration enregistrée. Vous pouvez relancer l’analyse dans le cockpit.','Chargement…','Traitement…','Retour au cockpit','La configuration du chiffrement est indisponible.'],en:['AI settings','Administration','OpenAI key','OpenAI model','Test connection','Save','Key configured','No key configured','A key is saved: leave this field empty to keep it.','The key is encrypted on the server and will never be displayed again. Testing and saving each send a short billable OpenAI request.','Connection successful.','Settings saved. You can run the cockpit analysis again.','Loading…','Working…','Back to cockpit','Encryption configuration is unavailable.'],de:['KI-Konfiguration','Verwaltung','OpenAI-Schlüssel','OpenAI-Modell','Verbindung testen','Speichern','Schlüssel konfiguriert','Kein Schlüssel konfiguriert','Schlüssel gespeichert: Feld leer lassen, um ihn zu behalten.','Der Schlüssel wird serverseitig verschlüsselt und nie erneut angezeigt. Testen und Speichern senden jeweils eine kurze kostenpflichtige OpenAI-Anfrage.','Verbindung erfolgreich.','Gespeichert. Sie können die Cockpit-Analyse neu starten.','Laden…','Verarbeitung…','Zurück zum Cockpit','Verschlüsselung nicht verfügbar.'],nl:['AI-instellingen','Beheer','OpenAI-sleutel','OpenAI-model','Verbinding testen','Opslaan','Sleutel ingesteld','Geen sleutel ingesteld','Sleutel opgeslagen: laat dit veld leeg om deze te behouden.','De sleutel wordt op de server versleuteld en nooit opnieuw getoond. Testen en opslaan versturen elk een kort betaald OpenAI-verzoek.','Verbinding geslaagd.','Opgeslagen. U kunt de analyse opnieuw starten.','Laden…','Bezig…','Terug naar cockpit','Versleuteling niet beschikbaar.']} as const;
const errors:Record<string,string>={invalid_key:'Clé refusée par OpenAI.',quota_or_rate_limit:'Quota ou limite OpenAI atteint. Vérifiez la facturation et réessayez.',model_unavailable:'Modèle indisponible pour cette clé.',access_denied:'Accès OpenAI refusé.',key_required:'Saisissez une clé OpenAI.',forbidden:'Cette page est réservée au propriétaire.',authentication_required:'Veuillez vous connecter.',invalid_input:'Vérifiez la clé et le modèle saisis.',try_later:'Patientez quelques secondes puis réessayez.',connection_failed:'Connexion OpenAI indisponible. Réessayez.',test_incomplete:'Le test n’a pas abouti. Vérifiez le modèle.',test_failed:'OpenAI a refusé le test. Vérifiez la clé et le modèle.'};
export default function AISettingsPanel(){const [lang]=useLanguage(),c=copy[lang];const [apiKey,setKey]=useState(''),[model,setModel]=useState(''),[configured,setConfigured]=useState(false),[canSave,setCanSave]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/admin/ai-settings',{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setConfigured(d.configured);setCanSave(d.canSave);setModel(d.model);}).catch(e=>{if(!controller.signal.aborted)setNotice(errors[e.message]||'Configuration indisponible. Actualisez la page pour réessayer.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 async function act(action:'test'|'save'){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/ai-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,apiKey,model}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(action==='save'?c[11]:c[10]);if(action==='save'){setKey('');setConfigured(true);}}catch(e){setNotice(errors[e instanceof Error?e.message:'']||'Opération impossible. Réessayez.');}finally{setBusy(false);}}
 return <main className="ai-settings"><a href="/admin">← {c[1]}</a><h1>{c[0]}</h1>{loading?<p>{c[12]}</p>:<section><p className={configured?'ai-configured':''}>{configured?c[6]:c[7]}</p><form onSubmit={e=>{e.preventDefault();void act('save');}} autoComplete="off"><label>{c[2]}<input type="password" name="openai-secret" autoComplete="new-password" spellCheck={false} maxLength={1024} value={apiKey} onChange={e=>setKey(e.target.value)} disabled={busy} placeholder={configured?c[8]:'sk-…'}/></label><label>{c[3]}<input value={model} onChange={e=>setModel(e.target.value)} maxLength={100} disabled={busy} required/></label><p className="ai-settings-help">{c[9]}</p>{!canSave&&<p>{c[15]}</p>}<div className="ai-settings-actions"><button type="button" onClick={()=>act('test')} disabled={busy||!model||(!apiKey&&!configured)}>{busy?c[13]:c[4]}</button><button type="submit" disabled={busy||!canSave||!model||(!apiKey&&!configured)}>{c[5]}</button></div></form></section>}<p role="status">{notice}</p><a href="/">{c[14]} →</a></main>;
}
