"use client";
import {useState,useEffect} from 'react';
import {Mail,Send,MessageSquare} from 'lucide-react';
import {useLanguage} from '@/lib/use-language';
import './contact-panel.css';
const texts={fr:['Contactez-nous','Une question ? Parlons-en.','Une question sur votre compte, une offre ou une idée pour le cockpit ? Écrivez à l’administration de Cockpit Marchés AI.','Votre message','Objet','Compte et connexion','Packs et abonnement','Suggestion','Autre question','Envoyer mon message','Envoi…','Votre message a bien été transmis à l’administration.','Connectez-vous pour envoyer votre demande depuis votre compte.','Envoi impossible. Votre texte est conservé ; veuillez réessayer.','Se connecter','Retour au cockpit','Écrire par e-mail','Vos demandes arrivent dans la boîte Feedback de l’administration de ce site.','Confidentialité','10 à 3 800 caractères. Ne transmettez pas de mot de passe, clé API ou numéro de carte.'],en:['Contact us','A question? Let’s talk.','Questions about your account, a plan or an idea for the cockpit? Write to Cockpit Marchés AI administration.','Your message','Subject','Account and sign-in','Plans and subscription','Suggestion','Other question','Send message','Sending…','Your message has been delivered to administration.','Sign in to send a request from your account.','Could not send. Your text is preserved; please retry.','Sign in','Back to cockpit','Send an email','Requests arrive in this site’s administration Feedback inbox.','Privacy','10–3,800 characters. Do not send passwords, API keys or card numbers.'],de:['Kontakt','Eine Frage? Sprechen wir darüber.','Fragen zum Konto, zu einem Tarif oder eine Idee für das Cockpit? Schreiben Sie an die Verwaltung von Cockpit Marchés AI.','Ihre Nachricht','Betreff','Konto und Anmeldung','Tarife und Abonnement','Vorschlag','Andere Frage','Nachricht senden','Wird gesendet…','Ihre Nachricht wurde an die Verwaltung übermittelt.','Melden Sie sich an, um eine Anfrage über Ihr Konto zu senden.','Senden fehlgeschlagen. Ihr Text bleibt erhalten; bitte erneut versuchen.','Anmelden','Zum Cockpit','E-Mail schreiben','Anfragen landen im Feedback-Postfach der Verwaltung dieser Website.','Datenschutz','10–3.800 Zeichen. Keine Passwörter, API-Schlüssel oder Kartennummern senden.'],nl:['Contact','Een vraag? Laten we praten.','Vragen over uw account, een pakket of een idee voor het cockpit? Schrijf naar het beheer van Cockpit Marchés AI.','Uw bericht','Onderwerp','Account en aanmelding','Pakketten en abonnement','Suggestie','Andere vraag','Bericht versturen','Versturen…','Uw bericht is afgeleverd bij het beheer.','Meld u aan om een verzoek vanuit uw account te sturen.','Versturen mislukt. Uw tekst blijft bewaard; probeer opnieuw.','Inloggen','Terug naar cockpit','E-mail sturen','Verzoeken komen in de Feedback-inbox van het beheer van deze site.','Privacy','10–3.800 tekens. Verstuur geen wachtwoorden, API-sleutels of kaartnummers.']} as const;
export default function ContactPanel({email}:{email:string}){const [lang]=useLanguage(),c=texts[lang];const [message,setMessage]=useState(''),[subject,setSubject]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState<'success'|'login'|'error'|null>(null);useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('cockpit-contact-draft')||'null');if(saved&&typeof saved.message==='string'&&saved.message.length<=3800){setMessage(saved.message);if(Number.isInteger(saved.subject)&&saved.subject>=0&&saved.subject<=3)setSubject(saved.subject);}}catch{}},[]);
 function remember(value:string,topic:number){try{sessionStorage.setItem('cockpit-contact-draft',JSON.stringify({message:value,subject:topic}));}catch{}}
 async function send(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setStatus(null);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`[Contact · ${c[5+subject]}]\n${message.trim()}`,category:'other',image:null,page:'/contact'})});if(r.status===401){setStatus('login');return;}if(!r.ok)throw Error();setStatus('success');setMessage('');try{sessionStorage.removeItem('cockpit-contact-draft');}catch{}}catch{setStatus('error');}finally{setBusy(false);}}
 return <main className="contact-space"><a href="/">← {c[15]}</a><div className="contact-hero"><span><MessageSquare size={28}/></span><small>SMARTDEV · COCKPIT MARCHÉS AI</small><h1>{c[0]}</h1><p>{c[1]}</p></div><div className="contact-grid"><section><h2>{c[1]}</h2><p>{c[2]}</p><p>{c[12]}</p>{email&&<a className="contact-email" href={'mailto:'+email}><Mail size={18}/>{c[16]}<small>{email}</small></a>}<p className="contact-note">{c[17]}</p><a href="/confidentialite">{c[18]} →</a></section><form onSubmit={send}><label>{c[4]}<select disabled={busy} value={subject} onChange={e=>{setSubject(Number(e.target.value));remember(message,Number(e.target.value));}}>{[0,1,2,3].map(i=><option key={i} value={i}>{c[5+i]}</option>)}</select></label><label>{c[3]}<textarea disabled={busy} minLength={10} maxLength={3800} required rows={8} value={message} onChange={e=>{setMessage(e.target.value);remember(e.target.value,subject);}}/></label><small>{c[19]}</small><p role="status">{status===null?'':c[status==='success'?11:status==='login'?12:13]}{status==='login'&&<> <a href="/account">{c[14]} →</a></>}</p><button disabled={busy||message.trim().length<10}><Send size={17}/>{busy?c[10]:c[9]}</button></form></div></main>;}
