"use client";
import {useState} from 'react';
import {useLanguage} from '@/lib/use-language';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './feedback.css';
const words={fr:['Votre avis','Signaler un problème ou proposer une amélioration','Message (10 à 4 000 caractères)','Joindre une capture','Capturer l’écran','Envoyer à l’administration','Fermer','Retirer','Votre retour a été transmis.','Connexion requise pour envoyer un retour.','Envoi impossible. Votre brouillon est conservé.','Capture indisponible ou annulée. Vous pouvez joindre une image.','Vérifiez la capture et masquez les informations sensibles avant l’envoi.','Anomalie','Idée','Données','Autre','Envoi…','Image trop volumineuse ou invalide.','Se connecter'],en:['Feedback','Report an issue or suggest an improvement','Message (10–4,000 characters)','Attach screenshot','Capture screen','Send to administration','Close','Remove','Your feedback has been delivered.','Sign in to send feedback.','Could not send. Your draft is preserved.','Capture unavailable or cancelled. You can attach an image.','Review the image and hide sensitive information before sending.','Bug','Idea','Data','Other','Sending…','Image too large or invalid.','Sign in'],de:['Feedback','Problem melden oder Verbesserung vorschlagen','Nachricht (10–4.000 Zeichen)','Screenshot anhängen','Bildschirm aufnehmen','An Verwaltung senden','Schließen','Entfernen','Feedback wurde übermittelt.','Bitte anmelden, um Feedback zu senden.','Senden fehlgeschlagen. Entwurf bleibt erhalten.','Aufnahme nicht verfügbar oder abgebrochen. Bild anhängen möglich.','Prüfen Sie das Bild und verbergen Sie sensible Informationen.','Fehler','Idee','Daten','Sonstiges','Wird gesendet…','Bild zu groß oder ungültig.','Anmelden'],nl:['Feedback','Meld een probleem of stel een verbetering voor','Bericht (10–4.000 tekens)','Screenshot toevoegen','Scherm vastleggen','Versturen naar beheer','Sluiten','Verwijderen','Uw feedback is afgeleverd.','Log in om feedback te versturen.','Versturen mislukt. Uw concept blijft bewaard.','Opname niet beschikbaar of geannuleerd. Voeg een afbeelding toe.','Controleer de afbeelding en verberg gevoelige informatie.','Probleem','Idee','Gegevens','Overig','Versturen…','Afbeelding te groot of ongeldig.','Inloggen']} as const;
function jpg(source:CanvasImageSource,w:number,h:number){if(!w||!h||w*h>60000000)throw Error('size');const canvas=document.createElement('canvas'),scale=Math.min(1,1600/w);canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);canvas.getContext('2d')!.drawImage(source,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/jpeg',.72);if(result.length>700000)throw Error('size');return result;}
export default function FeedbackCenter(){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[category,setCategory]=useState('bug'),[image,setImage]=useState(''),[busy,setBusy]=useState(false),[capturing,setCapturing]=useState(false),[notice,setNotice]=useState(''),[login,setLogin]=useState(false);const [lang]=useLanguage();const c=words[lang];

 async function attach(file?:File){if(!file)return;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw Error();const bitmap=await createImageBitmap(file);try{setImage(jpg(bitmap,bitmap.width,bitmap.height));setNotice('');}finally{bitmap.close();}}catch{setNotice(c[18]);}}
 async function capture(){let stream:MediaStream|undefined;try{setCapturing(true);stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const video=document.createElement('video');video.srcObject=stream;await video.play();await new Promise<void>(resolve=>setTimeout(resolve,300));setImage(jpg(video,video.videoWidth,video.videoHeight));setNotice('');}catch{setNotice(c[11]);}finally{stream?.getTracks().forEach(t=>t.stop());setCapturing(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');setLogin(false);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,category,image:image||null,page:location.pathname})});if(!r.ok){setLogin(r.status===401);throw Error(r.status===401?c[9]:c[10]);}setMessage('');setImage('');setNotice(c[8]);}catch(e){setNotice(e instanceof Error?e.message:c[10]);}finally{setBusy(false);}}
 return <><button className="feedback-launch" onClick={()=>setOpen(true)} aria-haspopup="dialog">✉ {c[0]}</button><Dialog open={open&&!capturing} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="feedback-panel" showCloseButton={false}><header><div><small>COCKPIT MARCHÉS AI</small><DialogTitle>{c[0]}</DialogTitle></div><button onClick={()=>setOpen(false)} disabled={busy} aria-label={c[6]}>×</button></header><DialogDescription>{c[1]}</DialogDescription><form onSubmit={submit}><label>{c[0]}<select value={category} onChange={e=>setCategory(e.target.value)}>{['bug','idea','data','other'].map((v,i)=><option key={v} value={v}>{c[13+i]}</option>)}</select></label><label>{c[2]}<textarea autoFocus required minLength={10} maxLength={4000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="feedback-actions"><label className="feedback-file">{c[3]}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void attach(e.target.files?.[0]);e.target.value='';}}/></label><button type="button" onClick={capture}>{c[4]}</button></div>{image&&<div><img className="feedback-preview" src={image} alt={c[3]}/><button type="button" onClick={()=>setImage('')}>{c[7]}</button></div>}<small>{c[12]}</small><p role="status">{notice}{login&&<> <a href="/account">{c[19]}</a></>}</p><button className="feedback-send" disabled={busy||message.trim().length<10}>{busy?c[17]:c[5]}</button></form></DialogContent></Dialog></>;
}
