"use client";
import {useEffect,useState} from 'react';
import './feedback.css';
import {useLanguage} from '@/lib/use-language';
const translations={fr:['Administration','ESPACE ADMINISTRATEUR','Retours utilisateurs','Messages et captures privés · Les 100 retours les plus récents de ce site.','Actualiser','Impossible de charger les retours. Vérifiez votre accès puis réessayez.','Chargement…','Aucun retour pour le moment.','Modification impossible. Réessayez.','Statut du retour','Nouveau','En cours','Résolu','Masquer','Voir la capture','Capture jointe au retour'],en:['Administration','ADMINISTRATOR AREA','User feedback','Private messages and screenshots · The 100 latest reports on this site.','Refresh','Unable to load feedback. Check your access and retry.','Loading…','No feedback yet.','Update failed. Please retry.','Feedback status','New','In progress','Resolved','Hide','View screenshot','Attached screenshot'],de:['Verwaltung','ADMINISTRATORBEREICH','Benutzerfeedback','Private Nachrichten und Bilder · Die 100 neuesten Meldungen dieser Website.','Aktualisieren','Feedback nicht verfügbar. Zugriff prüfen und erneut versuchen.','Laden…','Noch kein Feedback.','Änderung fehlgeschlagen. Erneut versuchen.','Feedbackstatus','Neu','In Bearbeitung','Erledigt','Ausblenden','Screenshot anzeigen','Angehängter Screenshot'],nl:['Beheer','BEHEERDERSRUIMTE','Gebruikersfeedback','Privéberichten en screenshots · De 100 nieuwste meldingen op deze site.','Vernieuwen','Feedback niet beschikbaar. Controleer uw toegang en probeer opnieuw.','Laden…','Nog geen feedback.','Wijziging mislukt. Probeer opnieuw.','Feedbackstatus','Nieuw','In behandeling','Opgelost','Verbergen','Screenshot bekijken','Bijgevoegde screenshot']} as const;
type Item={id:string;email:string;message:string;category:string;page:string;status:string;created_at:number;has_image:boolean|number};
export default function FeedbackInbox(){const [lang]=useLanguage(),c=translations[lang];const [items,setItems]=useState<Item[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[selected,setSelected]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/feedback',{cache:'no-store'});if(!r.ok)throw Error();setItems((await r.json()).items);setError('');}catch{setError(c[5]);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function status(id:string,value:string){setBusy(id);try{const r=await fetch('/api/admin/feedback',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:value})});if(!r.ok)throw Error();setItems(old=>old.map(x=>x.id===id?{...x,status:value}:x));setError('');}catch{setError(c[8]);}finally{setBusy('');}}
 return <main className="feedback-inbox"><a href="/admin">← {c[0]}</a><header><div><small>{c[1]}</small><h1>{c[2]}</h1><p>{c[3]}</p></div><button onClick={load} disabled={loading}>{c[4]}</button></header><p role="status">{error|| (loading?c[6]:items.length===0?c[7]:'')}</p>{items.map(x=><article key={x.id}><header><div><strong>{x.email}</strong><p>{x.category} · {new Date(Number(x.created_at)).toLocaleString()} · {x.page}</p></div><select aria-label={c[9]} value={x.status} disabled={busy===x.id} onChange={e=>status(x.id,e.target.value)}><option value="open">{c[10]}</option><option value="in_progress">{c[11]}</option><option value="resolved">{c[12]}</option></select></header><p style={{whiteSpace:'pre-wrap'}}>{x.message}</p>{!!x.has_image&&<><button onClick={()=>setSelected(selected===x.id?'':x.id)}>{selected===x.id?c[13]:c[14]}</button>{selected===x.id&&<img className="feedback-preview" src={'/api/admin/feedback/image?id='+encodeURIComponent(x.id)} alt={c[15]}/>}</>}</article>)}</main>;
}
