'use client';
import {useEffect,useState} from 'react';
import {useLanguage} from '@/lib/use-language';
import './ai-settings.css';
const words={
 fr:['Configuration Stripe','Administration','Mode test uniquement · SMARTDEV','Aucun paiement réel. Pro : 24 €/mois · Expert : 49 €/mois.','Clé API Stripe de test','Secret de signature du webhook','Tester la clé','Enregistrer et activer le mode test','Configuration de test enregistrée','Configuration incomplète','Laisser vide pour conserver le secret enregistré','Les secrets sont chiffrés côté serveur et ne sont jamais réaffichés.','Chargement…','Vérification…','Ouvrir les offres','Le chiffrement serveur doit être configuré avant l’enregistrement.','Clé vérifiée : les tarifs et Checkout sont accessibles. Aucun paiement effectué.','Configuration enregistrée. Effectuez maintenant un paiement de test et vérifiez le pack dans votre compte.','Dans votre tableau de bord Stripe, sélectionnez SMARTDEV et le mode test, puis ouvrez les clés API. Utilisez une clé restreinte de test (rk_test_) ; une clé secrète de test (sk_test_) fonctionne aussi.','Droits à autoriser : prix et produits en lecture, abonnements et factures en lecture, Checkout et portail client en écriture, clients en lecture/écriture.','Dans Workbench → Webhooks, ouvrez la destination correspondant exactement à cette adresse et copiez son secret de signature :','Le secret du webhook est propre à chaque site. La vérification de la clé ne confirme pas encore la réception des paiements.','Clé enregistrée','Webhook enregistré','À renseigner','Paiement d’essai : carte 4242 4242 4242 4242, date future et CVC à 3 chiffres.','La TVA sera configurée avant le passage en production.'],
 en:['Stripe settings','Administration','Test mode only · SMARTDEV','No real payments. Pro: €24/month · Expert: €49/month.','Stripe test API key','Webhook signing secret','Test key','Save and enable test mode','Test configuration saved','Configuration incomplete','Leave blank to keep the saved secret','Secrets are encrypted on the server and never displayed again.','Loading…','Checking…','Open plans','Server encryption must be configured before saving.','Key verified: prices and Checkout are accessible. No payment made.','Configuration saved. Make a test payment and check the plan in your account.','In Stripe, select SMARTDEV and test mode, then open API keys. Prefer a restricted test key (rk_test_); a secret test key (sk_test_) also works.','Permissions: read prices, products, subscriptions and invoices; write Checkout and customer portal; read/write customers.','In Workbench → Webhooks, open the destination matching this exact address and copy its signing secret:','Each site has its own webhook secret. Key verification does not yet confirm payment delivery.','Key saved','Webhook saved','Required','Test payment: card 4242 4242 4242 4242, future expiry and a 3-digit CVC.','Tax will be configured before going live.'],
 de:['Stripe-Konfiguration','Verwaltung','Nur Testmodus · SMARTDEV','Keine echten Zahlungen. Pro: 24 €/Monat · Expert: 49 €/Monat.','Stripe-Test-API-Schlüssel','Webhook-Signaturgeheimnis','Schlüssel testen','Speichern und Testmodus aktivieren','Testkonfiguration gespeichert','Konfiguration unvollständig','Leer lassen, um das gespeicherte Geheimnis zu behalten','Geheimnisse werden serverseitig verschlüsselt und nicht erneut angezeigt.','Laden…','Prüfen…','Tarife öffnen','Serververschlüsselung muss vor dem Speichern eingerichtet sein.','Schlüssel geprüft: Preise und Checkout sind zugänglich. Keine Zahlung ausgeführt.','Gespeichert. Führen Sie eine Testzahlung durch und prüfen Sie den Tarif im Konto.','Wählen Sie in Stripe SMARTDEV und den Testmodus, dann API-Schlüssel. Verwenden Sie bevorzugt einen eingeschränkten Testschlüssel (rk_test_); sk_test_ funktioniert ebenfalls.','Berechtigungen: Preise, Produkte, Abonnements und Rechnungen lesen; Checkout und Kundenportal schreiben; Kunden lesen/schreiben.','Öffnen Sie in Workbench → Webhooks das Ziel mit genau dieser Adresse und kopieren Sie das Signaturgeheimnis:','Jede Website hat ein eigenes Webhook-Geheimnis. Der Schlüsseltest bestätigt noch keinen Zahlungseingang.','Schlüssel gespeichert','Webhook gespeichert','Erforderlich','Testkarte: 4242 4242 4242 4242, zukünftiges Ablaufdatum und dreistellige CVC.','Steuern werden vor dem Produktivbetrieb eingerichtet.'],
 nl:['Stripe-instellingen','Beheer','Alleen testmodus · SMARTDEV','Geen echte betalingen. Pro: €24/maand · Expert: €49/maand.','Stripe-test-API-sleutel','Webhook-ondertekeningsgeheim','Sleutel testen','Opslaan en testmodus activeren','Testconfiguratie opgeslagen','Configuratie onvolledig','Leeg laten om het opgeslagen geheim te behouden','Geheimen worden op de server versleuteld en nooit opnieuw getoond.','Laden…','Controleren…','Pakketten openen','Serverversleuteling moet eerst worden ingesteld.','Sleutel gecontroleerd: prijzen en Checkout zijn beschikbaar. Geen betaling uitgevoerd.','Opgeslagen. Voer een testbetaling uit en controleer het pakket in uw account.','Selecteer SMARTDEV en de testmodus in Stripe en open API-sleutels. Gebruik bij voorkeur een beperkte testsleutel (rk_test_); sk_test_ werkt ook.','Rechten: prijzen, producten, abonnementen en facturen lezen; Checkout en klantenportaal schrijven; klanten lezen/schrijven.','Open in Workbench → Webhooks de bestemming met precies dit adres en kopieer het ondertekeningsgeheim:','Elke site heeft een eigen webhook-geheim. De sleuteltest bevestigt nog niet de ontvangst van betalingen.','Sleutel opgeslagen','Webhook opgeslagen','Vereist','Testkaart: 4242 4242 4242 4242, toekomstige vervaldatum en driecijferige CVC.','Belastingen worden ingesteld voor de productiemodus.']
} as const;
const errors:Record<string,readonly string[]>={
 test_key_required:['Utilisez uniquement une clé de test rk_test_ ou sk_test_.','Use only an rk_test_ or sk_test_ key.','Nur rk_test_ oder sk_test_ verwenden.','Gebruik alleen rk_test_ of sk_test_.'],
 webhook_required:['Ajoutez le secret du webhook de ce site.','Add this site’s webhook secret.','Webhook-Geheimnis dieser Website eintragen.','Voeg het webhook-geheim van deze site toe.'],
 invalid_webhook_secret:['Le secret doit commencer par whsec_.','The secret must begin with whsec_.','Das Geheimnis muss mit whsec_ beginnen.','Het geheim moet beginnen met whsec_.'],
 missing_permissions:['La clé ne dispose pas des droits Stripe requis.','The key lacks required Stripe permissions.','Dem Schlüssel fehlen Stripe-Berechtigungen.','De sleutel mist vereiste Stripe-rechten.'],
 wrong_account_or_prices:['Cette clé ne correspond pas aux tarifs SMARTDEV attendus.','This key does not match the expected SMARTDEV prices.','Schlüssel passt nicht zu den SMARTDEV-Preisen.','De sleutel hoort niet bij de verwachte SMARTDEV-prijzen.'],
 try_later:['Patientez cinq secondes avant de réessayer.','Wait five seconds before retrying.','Bitte fünf Sekunden warten.','Wacht vijf seconden.'],
 generic:['Opération impossible. Vérifiez la clé, les droits et votre connexion propriétaire. La configuration précédente est conservée.','Unable to complete. Check the key, permissions and owner sign-in. Previous settings are preserved.','Nicht möglich. Schlüssel, Rechte und Eigentümeranmeldung prüfen. Vorherige Einstellungen bleiben erhalten.','Niet mogelijk. Controleer sleutel, rechten en eigenaarslogin. Vorige instellingen blijven behouden.']
};
type Status={configured:boolean;keyConfigured:boolean;webhookConfigured:boolean;managedWebhook?:boolean;canSave:boolean};
export default function StripeSettingsPanel(){const [lang]=useLanguage(),c=words[lang],idx=['fr','en','de','nl'].indexOf(lang);const [status,setStatus]=useState<Status|null>(null),[apiKey,setKey]=useState(''),[webhookSecret,setWebhook]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[endpoint,setEndpoint]=useState('');
 useEffect(()=>{const ctrl=new AbortController();setEndpoint(location.origin+'/api/billing/webhook');fetch('/api/admin/stripe-settings',{cache:'no-store',signal:ctrl.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error();setStatus(d);}).catch(()=>{if(!ctrl.signal.aborted)setNotice(errors.generic[idx]);});return()=>ctrl.abort();},[idx]);
 async function act(action:'test'|'save'){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/stripe-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,apiKey,webhookSecret}),signal:AbortSignal.timeout(90000)});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(action==='save'?c[17]:c[16]);if(action==='save'){setKey('');setWebhook('');setStatus(previous=>({...previous,configured:true,keyConfigured:true,webhookConfigured:true,canSave:true}));}}catch(e){setNotice((errors[e instanceof Error?e.message:'']||errors.generic)[idx]);}finally{setBusy(false);}}
 return <main className="ai-settings"><a href="/admin">← {c[1]}</a><h1>{c[0]}</h1><p className="ai-configured">{c[2]}</p><p>{c[3]}</p><section><p>{c[18]}</p><p className="ai-settings-help">{c[19]}</p><p>{c[20]}</p><code style={{overflowWrap:'anywhere',fontSize:14}}>{endpoint}</code><p className="ai-settings-help">{c[21]}</p>{!status?<p>{c[12]}</p>:<><p>{status.configured?c[8]:c[9]}</p>{status.managedWebhook&&<p>{['Secret webhook configuré directement et sécurisé sur cet hébergement.','Webhook secret configured securely on this hosting.','Webhook-Geheimnis sicher auf diesem Hosting konfiguriert.','Webhookgeheim veilig ingesteld op deze hosting.'][idx]}</p>}<form autoComplete="off" onSubmit={e=>{e.preventDefault();void act('save');}}><label>{c[4]} · {status.keyConfigured?c[22]:c[24]}<input type="password" name="stripe-test-secret" autoComplete="new-password" spellCheck={false} maxLength={1024} disabled={busy} value={apiKey} onChange={e=>setKey(e.target.value)} placeholder={status.keyConfigured?c[10]:'rk_test_…'}/></label><label>{c[5]} · {status.webhookConfigured?c[23]:c[24]}<input type="password" name="stripe-webhook-secret" autoComplete="new-password" spellCheck={false} maxLength={1024} disabled={busy||status.managedWebhook} value={webhookSecret} onChange={e=>setWebhook(e.target.value)} placeholder={status.webhookConfigured?c[10]:'whsec_…'}/></label><p className="ai-settings-help">{c[11]}</p>{!status.canSave&&<p>{c[15]}</p>}<div className="ai-settings-actions"><button type="button" disabled={busy||(!apiKey&&!status.keyConfigured)} onClick={()=>void act('test')}>{busy?c[13]:c[6]}</button><button type="submit" disabled={busy||!status.canSave||(!apiKey&&!status.keyConfigured)||(!webhookSecret&&!status.webhookConfigured)}>{c[7]}</button></div></form></>}</section><p role="status">{notice}</p><p>{c[25]}</p><a href="/pricing">{c[14]} →</a><p className="ai-settings-help">{c[26]}</p></main>;
}
