"use client";
import {useEffect,useState} from 'react';
import {useLanguage} from '@/lib/use-language';
import {Sparkles,ChevronDown,Crown,LayoutDashboard,UserRound} from 'lucide-react';
import './usage-beacon.css';
import {usePathname} from 'next/navigation';
type Quota={used:number;limit:number|null;remaining:number|null;resetAt:number};
type Member={plan:string;status:string;suspended:boolean};
const words={fr:['Découverte','restantes','Consommation IA','Renouvellement le','Gérer mon pack','Données indisponibles · réessayer','Accès administrateur','analyses utilisées','Suspendu','Actualisation…'],en:['Discovery','left','AI usage','Renews on','Manage my plan','Unavailable · retry','Administrator access','analyses used','Suspended','Updating…'],de:['Entdecken','übrig','KI-Verbrauch','Erneuerung am','Tarif verwalten','Nicht verfügbar · erneut versuchen','Administratorzugang','Analysen verwendet','Gesperrt','Aktualisierung…'],nl:['Ontdekking','over','AI-verbruik','Vernieuwd op','Pakket beheren','Niet beschikbaar · opnieuw proberen','Beheerderstoegang','analyses gebruikt','Geschorst','Bijwerken…']} as const;
export default function UsageBeacon(){
 const [lang]=useLanguage(),c=words[lang],path=usePathname();const navigation={fr:['Navigation principale','Cockpit','Mon compte'],en:['Main navigation','Cockpit','My account'],de:['Hauptnavigation','Cockpit','Mein Konto'],nl:['Hoofdnavigatie','Cockpit','Mijn account']}[lang];
 const [member,setMember]=useState<Member|null>(null),[quota,setQuota]=useState<Quota|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true,sequence=0;const controller=new AbortController();async function load(){const id=++sequence;setBusy(true);try{const [m,q]=await Promise.all([fetch('/api/billing/membership',{cache:'no-store',signal:controller.signal}),fetch('/api/ai-allowance',{cache:'no-store',signal:controller.signal})]);if(!m.ok)throw Error();const membership=(await m.json()).membership;if(!alive||id!==sequence)return;setMember(membership);if(!membership){setQuota(null);setError(false);return;}if(!q.ok)throw Error();const next=await q.json();if(!alive||id!==sequence)return;setQuota(next);setError(false);}catch{if(alive&&id===sequence){setError(true);setQuota(null);}}finally{if(alive&&id===sequence)setBusy(false);}}
 const visible=()=>{if(document.visibilityState==='visible')void load();};void load();window.addEventListener('ai-usage-changed',visible);window.addEventListener('focus',visible);document.addEventListener('visibilitychange',visible);const interval=setInterval(visible,60000);return()=>{alive=false;controller.abort();clearInterval(interval);window.removeEventListener('ai-usage-changed',visible);window.removeEventListener('focus',visible);document.removeEventListener('visibilitychange',visible);};},[retry]);

 const active=['active','trialing'].includes(member?.status.toLowerCase()||''),raw=member?.plan.toLowerCase()||'',tier=active?(['expert','trader_plus'].includes(raw)?'expert':raw==='pro'?'pro':'free'):'free';
 const name=tier==='expert'?'Expert / Trader+':tier==='pro'?'Pro':c[0];
 const percent=quota?.limit?Math.max(0,Math.min(100,100*(quota.remaining??0)/quota.limit)):100;
 return <aside className={"usage-beacon "+(member?"has-member":"")} aria-label={navigation[0]}><nav className="usage-navigation" aria-label={navigation[0]}><a href="/" aria-current={path==='/'?'page':undefined}><LayoutDashboard size={17}/><span>{navigation[1]}</span></a><a href="/account" aria-current={path?.startsWith('/account')?'page':undefined}><UserRound size={17}/><span>{navigation[2]}</span></a></nav>{member&&<div className="usage-member"><a className={'usage-pack '+tier} href="/account"><Crown size={16}/><span>{name}</span>{member.suspended&&<small>{c[8]}</small>}</a><details className="usage-details"><summary><Sparkles size={16}/><span className="usage-short" aria-live="polite">{busy?c[9]:error?c[2]+' —':quota?.limit===null?'IA ∞':quota?`${quota.remaining} / ${quota.limit} IA ${c[1]}`:'IA —'}</span>{quota&&!error&&<span className={'usage-track '+(percent<=20?'low':'')} aria-hidden="true"><i style={{width:percent+'%'}}/></span>}<ChevronDown size={14}/></summary><div className="usage-popover"><strong>{c[2]}</strong>{error?<button onClick={()=>setRetry(n=>n+1)}>{c[5]}</button>:quota&&<>{quota.limit===null?<p>{c[6]}</p>:<><p><b>{quota.used} / {quota.limit}</b> {c[7]}</p><p>{c[3]} <b>{new Date(quota.resetAt).toLocaleDateString(lang,{timeZone:'UTC'})}</b></p></>}</>}<a href="/account">{c[4]} →</a></div></details></div>}</aside>;
}
