import type{SupportedLocale}from'./account-types';

const copies={
 fr:{account:'Mon compte',profile:'Profil',subscription:'Abonnement',manageProfile:'Gérez vos informations personnelles et votre langue.',manageSubscription:'Consultez votre formule et son état.',name:'Nom affiché',email:'E-mail',language:'Langue',avatar:'URL de l’avatar (facultatif)',save:'Enregistrer',saving:'Enregistrement…',saved:'Profil enregistré',error:'Impossible d’enregistrer le profil.',plan:'Formule',status:'Statut',role:'Rôle',offers:'Voir les offres',logout:'Se déconnecter',back:'Retour au cockpit',secure:'Vos rôles et votre formule sont contrôlés côté serveur.',suspendedTitle:'Compte suspendu',suspendedText:'Votre accès est temporairement suspendu. Contactez le support pour obtenir de l’aide.',unavailableTitle:'Compte temporairement indisponible',unavailableText:'Le service de compte ne répond pas actuellement. Réessayez dans quelques instants.'},
 en:{account:'My account',profile:'Profile',subscription:'Subscription',manageProfile:'Manage your personal details and language.',manageSubscription:'Review your plan and its status.',name:'Display name',email:'Email',language:'Language',avatar:'Avatar URL (optional)',save:'Save',saving:'Saving…',saved:'Profile saved',error:'Unable to save the profile.',plan:'Plan',status:'Status',role:'Role',offers:'View plans',logout:'Sign out',back:'Back to cockpit',secure:'Your role and plan are controlled on the server.',suspendedTitle:'Account suspended',suspendedText:'Your access is temporarily suspended. Contact support for assistance.',unavailableTitle:'Account temporarily unavailable',unavailableText:'The account service is currently unavailable. Please try again shortly.'},
 de:{account:'Mein Konto',profile:'Profil',subscription:'Abonnement',manageProfile:'Verwalten Sie Ihre persönlichen Daten und Sprache.',manageSubscription:'Prüfen Sie Ihren Tarif und Status.',name:'Anzeigename',email:'E-Mail',language:'Sprache',avatar:'Avatar-URL (optional)',save:'Speichern',saving:'Speichern…',saved:'Profil gespeichert',error:'Das Profil konnte nicht gespeichert werden.',plan:'Tarif',status:'Status',role:'Rolle',offers:'Tarife ansehen',logout:'Abmelden',back:'Zurück zum Cockpit',secure:'Rolle und Tarif werden serverseitig kontrolliert.',suspendedTitle:'Konto gesperrt',suspendedText:'Ihr Zugriff ist vorübergehend gesperrt. Wenden Sie sich an den Support.',unavailableTitle:'Konto vorübergehend nicht verfügbar',unavailableText:'Der Kontodienst ist derzeit nicht verfügbar. Versuchen Sie es später erneut.'},
 nl:{account:'Mijn account',profile:'Profiel',subscription:'Abonnement',manageProfile:'Beheer uw persoonlijke gegevens en taal.',manageSubscription:'Bekijk uw formule en status.',name:'Weergavenaam',email:'E-mail',language:'Taal',avatar:'Avatar-URL (optioneel)',save:'Opslaan',saving:'Opslaan…',saved:'Profiel opgeslagen',error:'Het profiel kon niet worden opgeslagen.',plan:'Formule',status:'Status',role:'Rol',offers:'Bekijk formules',logout:'Uitloggen',back:'Terug naar cockpit',secure:'Uw rol en formule worden op de server gecontroleerd.',suspendedTitle:'Account geschorst',suspendedText:'Uw toegang is tijdelijk geschorst. Neem contact op met support.',unavailableTitle:'Account tijdelijk niet beschikbaar',unavailableText:'De accountservice is momenteel niet beschikbaar. Probeer het later opnieuw.'},
}as const;
export function accountCopy(locale:SupportedLocale){return copies[locale]||copies.fr;}
