import{neon}from'@neondatabase/serverless';
import{getUserSyncStore}from'./user-sync-store';
import{getUserWorkspace}from'./user-workspace-store';
import{getBillingState,hasPaidEntitlement}from'./billing-store';
import{stripeDelete}from'./stripe-rest';

function connectionString(){return process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NEON_DATABASE_URL||process.env.NEON_POSTGRES_URL||'';}
function sql(){const url=connectionString();if(!url)throw new Error('storage_not_configured');return neon(url);}

export async function exportUserData(user:{id:string;email:string;displayName:string}){const store=getUserSyncStore();const[snapshot,devices,paperTrades,decisionNotes,workspace,billing]=await Promise.all([store.getSnapshot(user.id),store.listNotificationDevices(user.id),store.listPaperTrades(user.id),store.listDecisionNotes(user.id),getUserWorkspace(user.id),getBillingState(user.id)]);return{exportedAt:new Date().toISOString(),identity:{id:user.id,email:user.email,displayName:user.displayName},watchlist:snapshot.watchlist,notificationPreferences:snapshot.notificationPreferences,readNotificationIds:snapshot.readNotificationIds,notificationDevices:devices.map(d=>({id:d.id,platform:d.platform,provider:d.provider,createdAt:d.createdAt,updatedAt:d.updatedAt})),paperTrades,decisionNotes,workspace,billing:{plan:billing.plan,status:billing.status,currentPeriodEnd:billing.currentPeriodEnd,cancelAtPeriodEnd:billing.cancelAtPeriodEnd}};}

export async function eraseUserData(userId:string){const billing=await getBillingState(userId);if(hasPaidEntitlement(billing))throw new Error('active_subscription_must_be_cancelled');if(billing.stripeCustomerId)await stripeDelete(`/customers/${encodeURIComponent(billing.stripeCustomerId)}`,`erase-customer:${userId}`);const db=sql();await db`delete from mobile_pairing_codes where user_id=${userId}`;await db`delete from notification_deliveries where user_id=${userId}`;await db`delete from notification_devices where user_id=${userId}`;await db`delete from notification_reads where user_id=${userId}`;await db`delete from notification_preferences where user_id=${userId}`;await db`delete from watchlist_items where user_id=${userId}`;await db`delete from paper_trades where user_id=${userId}`;await db`delete from decision_notes where user_id=${userId}`;await db`delete from user_workspace_state where user_id=${userId}`;await db`delete from billing_subscriptions where user_id=${userId}`;await db`delete from web_credentials where user_id=${userId}`;await db`delete from user_profiles where id=${userId}`;return{ok:true,deletedAt:new Date().toISOString()};}
