import{neon}from'@neondatabase/serverless';
import type{AccountStatus,CommercialPlan,UserRole}from'./account-types';

function sqlClient(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NEON_DATABASE_URL||process.env.NEON_POSTGRES_URL;if(!url)throw new Error('storage_not_configured');return neon(url);}
export type AdminUser={id:string;displayName:string;email:string;role:UserRole;accountStatus:AccountStatus;plan:CommercialPlan;subscriptionStatus:AccountStatus;lastLoginAt:number|null;createdAt:number};
export type AdminChange={action:'SET_PLAN';plan:CommercialPlan}|{action:'SET_SUBSCRIPTION_STATUS';subscriptionStatus:AccountStatus}|{action:'SET_ROLE';role:'USER'|'SUPPORT'}|{action:'SET_STATUS';status:'ACTIVE'|'SUSPENDED'};

export async function listAdminUsers(query:string,status:string,limit=50):Promise<AdminUser[]>{const sql=sqlClient(),needle=`%${query.trim()}%`;const rows=await sql`select p.id,p.display_name,p.email,p.role,p.account_status,s.plan,s.status as subscription_status,p.last_login_at,p.created_at from user_profiles p join subscriptions s on s.user_id=p.id where (${query.trim()}='' or p.email ilike ${needle} or p.display_name ilike ${needle}) and (${status}='' or p.account_status=${status} or s.plan=${status} or p.role=${status}) order by coalesce(p.last_login_at,p.created_at) desc limit ${limit}`;return rows.map((row:any)=>({id:String(row.id),displayName:String(row.display_name),email:String(row.email),role:row.role,accountStatus:row.account_status,plan:row.plan,subscriptionStatus:row.subscription_status,lastLoginAt:row.last_login_at==null?null:Number(row.last_login_at),createdAt:Number(row.created_at)}));}

export async function listAdminAudit(limit=100){const sql=sqlClient();return sql`select l.id,l.action,l.reason,l.before,l.after,l.created_at,a.email as actor_email,t.email as target_email from admin_audit_logs l join user_profiles a on a.id=l.actor_user_id left join user_profiles t on t.id=l.target_user_id order by l.created_at desc limit ${limit}`;}

export async function consumeAdminAction(actorUserId:string){const sql=sqlClient(),now=Date.now(),windowStart=Math.floor(now/60000)*60000,windowEnd=windowStart+60000,id=`admin:${actorUserId}:${windowStart}`;const rows=await sql`insert into usage_counters(id,user_id,feature,window_start,window_end,usage_count,created_at,updated_at) values(${id},${actorUserId},'ADMIN_PANEL',${windowStart},${windowEnd},1,${now},${now}) on conflict(user_id,feature,window_start) do update set usage_count=usage_counters.usage_count+1,updated_at=${now} returning usage_count`;if(Number(rows[0]?.usage_count)>30)throw new Error('rate_limited');}

export async function applyAdminChange(actorUserId:string,targetUserId:string,change:AdminChange,reason:string){const sql=sqlClient(),now=Date.now(),auditId=crypto.randomUUID();if(actorUserId===targetUserId&&change.action!=='SET_PLAN')throw new Error('self_access_change_forbidden');
 if(change.action==='SET_PLAN'){const rows=await sql`with previous as(select user_id,plan,status from subscriptions where user_id=${targetUserId}),updated as(update subscriptions set plan=${change.plan},updated_at=${now} where user_id=${targetUserId} returning user_id,plan,status),logged as(insert into admin_audit_logs(id,actor_user_id,target_user_id,action,before,after,reason,created_at) select ${auditId},${actorUserId},${targetUserId},'SET_PLAN',jsonb_build_object('plan',previous.plan,'status',previous.status),jsonb_build_object('plan',updated.plan,'status',updated.status),${reason},${now} from previous join updated using(user_id)) select * from updated`;if(!rows[0])throw new Error('target_not_found');return;}
 if(change.action==='SET_SUBSCRIPTION_STATUS'){const rows=await sql`with previous as(select user_id,plan,status from subscriptions where user_id=${targetUserId}),updated as(update subscriptions set status=${change.subscriptionStatus},updated_at=${now} where user_id=${targetUserId} returning user_id,plan,status),logged as(insert into admin_audit_logs(id,actor_user_id,target_user_id,action,before,after,reason,created_at) select ${auditId},${actorUserId},${targetUserId},'SET_SUBSCRIPTION_STATUS',jsonb_build_object('plan',previous.plan,'status',previous.status),jsonb_build_object('plan',updated.plan,'status',updated.status),${reason},${now} from previous join updated using(user_id)) select * from updated`;if(!rows[0])throw new Error('target_not_found');return;}
 if(change.action==='SET_ROLE'){const rows=await sql`with previous as(select id,role,account_status from user_profiles where id=${targetUserId}),guarded as(select * from previous where role<>'ADMIN' or (select count(*) from user_profiles where role='ADMIN' and account_status<>'SUSPENDED')>1),updated as(update user_profiles set role=${change.role},updated_at=${now} where id in(select id from guarded) returning id,role,account_status),logged as(insert into admin_audit_logs(id,actor_user_id,target_user_id,action,before,after,reason,created_at) select ${auditId},${actorUserId},${targetUserId},'SET_ROLE',jsonb_build_object('role',previous.role),jsonb_build_object('role',updated.role),${reason},${now} from previous join updated using(id)) select * from updated`;if(!rows[0])throw new Error('last_admin_protected');return;}
 const rows=await sql`with previous as(select id,role,account_status from user_profiles where id=${targetUserId}),guarded as(select * from previous where ${change.status}<>'SUSPENDED' or role<>'ADMIN' or (select count(*) from user_profiles where role='ADMIN' and account_status<>'SUSPENDED')>1),updated as(update user_profiles set account_status=${change.status},updated_at=${now} where id in(select id from guarded) returning id,role,account_status),logged as(insert into admin_audit_logs(id,actor_user_id,target_user_id,action,before,after,reason,created_at) select ${auditId},${actorUserId},${targetUserId},'SET_STATUS',jsonb_build_object('status',previous.account_status),jsonb_build_object('status',updated.account_status),${reason},${now} from previous join updated using(id)) select * from updated`;if(!rows[0])throw new Error('last_admin_protected');
}
