export type IndicatorPoint={t:number;price:number;high?:number;low?:number};
export type IndicatorDecision='ACHETER'|'VENDRE'|'ATTENDRE'|'INDISPONIBLE';
export type IndicatorItem={name:string;value:string;reading:string;decision:IndicatorDecision;explanation:string};

function ema(values:number[],period:number){if(!values.length)return null;const alpha=2/(period+1);return values.reduce((value,next,index)=>index?next*alpha+value*(1-alpha):next,values[0]);}
function midpoint(points:IndicatorPoint[],end:number,period:number){const window=points.slice(Math.max(0,end-period+1),end+1);const highs=window.map(p=>Number.isFinite(p.high)?Number(p.high):p.price),lows=window.map(p=>Number.isFinite(p.low)?Number(p.low):p.price);return(Math.max(...highs)+Math.min(...lows))/2;}
function fmt(value:number|null,digits=5){return value===null||!Number.isFinite(value)?'—':value.toFixed(digits);}

export function buildIndicatorCenter(points:IndicatorPoint[],snapshot:{ema20?:number|null;ema50?:number|null;rsi?:number|null;support?:number|null;resistance?:number|null;last?:number|null}){
 const unavailable=(name:string,value='—',explanation='Historique insuffisant pour produire une lecture fiable.'):IndicatorItem=>({name,value,reading:'Indisponible',decision:'INDISPONIBLE',explanation});
 const wait=(name:string,value:string,reading:string,explanation:string):IndicatorItem=>({name,value,reading,decision:'ATTENDRE',explanation});
 const directional=(name:string,value:string,bullish:boolean,reading:string,explanation:string):IndicatorItem=>({name,value,reading,decision:bullish?'ACHETER':'VENDRE',explanation});
 let ichimoku:any=null;
 if(points.length>=52){
  const data=points.map((point,index)=>{const tenkan=index>=8?midpoint(points,index,9):null,kijun=index>=25?midpoint(points,index,26):null,spanB=index>=51?midpoint(points,index,52):null;return{...point,tenkan,kijun,spanA:tenkan!==null&&kijun!==null?(tenkan+kijun)/2:null,spanB};});
  const latest=data.at(-1),prices=points.map(p=>p.price),cloudTop=Math.max(latest.spanA??latest.price,latest.spanB??latest.price),cloudBottom=Math.min(latest.spanA??latest.price,latest.spanB??latest.price),cloudWidth=latest.price?((cloudTop-cloudBottom)/latest.price)*100:0,cloudPosition=latest.price>cloudTop?'au-dessus':latest.price<cloudBottom?'en dessous':'dans',cross=(latest.tenkan??0)>(latest.kijun??0)?'haussier':'baissier',cloudDirection=(latest.spanA??0)>(latest.spanB??0)?'haussier':'baissier',macd=(ema(prices.slice(-80),12)??0)-(ema(prices.slice(-80),26)??0),last20=prices.slice(-20),mean=last20.reduce((s,v)=>s+v,0)/last20.length,deviation=Math.sqrt(last20.reduce((s,v)=>s+Math.pow(v-mean,2),0)/last20.length),bollingerUpper=mean+deviation*2,bollingerLower=mean-deviation*2,atrWindow=points.slice(-14),atr=atrWindow.reduce((s,p)=>s+((p.high??p.price)-(p.low??p.price)),0)/atrWindow.length,shape=cloudWidth<.18?'nuage comprimé':cloudWidth>1.2?'nuage épais':'nuage équilibré',bias=cloudPosition==='au-dessus'&&cross==='haussier'&&cloudDirection==='haussier'?'HAUSSIER':cloudPosition==='en dessous'&&cross==='baissier'&&cloudDirection==='baissier'?'BAISSIER':'MIXTE';
  ichimoku={data:data.slice(-80),tenkan:latest.tenkan,kijun:latest.kijun,spanA:latest.spanA,spanB:latest.spanB,chikou:points.at(-27)?.price??null,cloudPosition,cross,cloudDirection,cloudWidth,shape,macd,bollingerUpper,bollingerLower,atr,bias};
 }
 const last=snapshot.last??points.at(-1)?.price??null;
 const items:IndicatorItem[]=[
  ichimoku?{name:'Ichimoku Kinko Hyo',value:`${ichimoku.shape} · ${ichimoku.cloudWidth.toFixed(2)} %`,reading:`Prix ${ichimoku.cloudPosition} le nuage · croisement ${ichimoku.cross}`,decision:ichimoku.bias==='HAUSSIER'?'ACHETER':ichimoku.bias==='BAISSIER'?'VENDRE':'ATTENDRE',explanation:'Preuve principale : position du prix, croisement Tenkan/Kijun et orientation du nuage.'}:unavailable('Ichimoku Kinko Hyo','52 observations requises'),
  snapshot.ema20==null||snapshot.ema50==null?unavailable('EMA 20 / EMA 50'):directional('EMA 20 / EMA 50',`${fmt(snapshot.ema20)} / ${fmt(snapshot.ema50)}`,snapshot.ema20>snapshot.ema50,snapshot.ema20>snapshot.ema50?'Tendance haussière':'Tendance baissière','Le croisement des moyennes estime la direction dominante ; il ne confirme pas seul un point d’entrée.'),
  snapshot.rsi==null?unavailable('RSI 14'):snapshot.rsi<=30?directional('RSI 14',snapshot.rsi.toFixed(1),true,'Zone de survente','Un rebond devient possible, mais une confirmation du prix reste nécessaire.'):snapshot.rsi>=70?directional('RSI 14',snapshot.rsi.toFixed(1),false,'Zone de surachat','Le risque de correction augmente ; attendre une confirmation avant toute vente.'):wait('RSI 14',snapshot.rsi.toFixed(1),'Zone équilibrée','Le RSI ne donne pas actuellement de signal extrême exploitable.'),
  ichimoku?directional('MACD 12 / 26',fmt(ichimoku.macd),ichimoku.macd>=0,ichimoku.macd>=0?'Momentum positif':'Momentum négatif','L’écart entre les moyennes rapides et lentes mesure l’impulsion dominante.'):unavailable('MACD 12 / 26'),
  ichimoku&&last!==null?(last<=ichimoku.bollingerLower?directional('Bandes de Bollinger',`${fmt(ichimoku.bollingerLower,4)} — ${fmt(ichimoku.bollingerUpper,4)}`,true,'Prix sur la bande basse','Une réintégration de la bande peut soutenir un rebond technique.'):last>=ichimoku.bollingerUpper?directional('Bandes de Bollinger',`${fmt(ichimoku.bollingerLower,4)} — ${fmt(ichimoku.bollingerUpper,4)}`,false,'Prix sur la bande haute','Le prix est étiré ; surveiller un rejet ou une consolidation.'):wait('Bandes de Bollinger',`${fmt(ichimoku.bollingerLower,4)} — ${fmt(ichimoku.bollingerUpper,4)}`,'Prix à l’intérieur des bandes','Aucun excès statistique n’est détecté sur la période active.')):unavailable('Bandes de Bollinger'),
  ichimoku?wait('ATR 14',fmt(ichimoku.atr),'Mesure de risque','L’ATR mesure l’amplitude et sert au dimensionnement du risque ; il n’indique jamais seul acheter ou vendre.'):unavailable('ATR 14'),
  snapshot.support==null||snapshot.resistance==null?unavailable('Supports / Résistances'):wait('Supports / Résistances',`${fmt(snapshot.support)} / ${fmt(snapshot.resistance)}`,'Zone active',`Acheter exige une cassure confirmée au-dessus de ${fmt(snapshot.resistance)} ; vendre exige une rupture confirmée sous ${fmt(snapshot.support)}.`),
 ];
 const buy=items.filter(i=>i.decision==='ACHETER').length,sell=items.filter(i=>i.decision==='VENDRE').length,hold=items.filter(i=>i.decision==='ATTENDRE').length;
 const consensus:IndicatorDecision=buy>sell&&buy>hold?'ACHETER':sell>buy&&sell>hold?'VENDRE':'ATTENDRE';
 return{items,consensus,counts:{buy,sell,wait:hold},ichimoku};
}
