import type { Lang } from "./i18n";

const fr = {
  title: "Votre fil d’analyse", intro: "Comprendre la lecture, comparer les horizons, puis garder une trace.",
  understand: "Comprendre", compare: "Comparer", follow: "Suivre", next: "Étape suivante",
  reading: "Lecture sur la période choisie", bullish: "Orientation haussière", bearish: "Orientation baissière", neutral: "Conditions à confirmer",
  loading: "Les données de cette sélection se chargent…", unavailable: "La lecture de cette sélection n’est pas disponible.", stale: "Les données sont anciennes : actualisez avant de conserver cette lecture.",
  refresh: "Actualiser les données", details: "Voir l’explication complète", news: "Vérifier les actualités", source: "Source des cours", date: "Dernière donnée", unknown: "Non renseigné",
  ai: "Lecture IA", technical: "Lecture technique", confidence: "Le score décrit l’alignement estimé des signaux. Ce n’est pas une probabilité de gain.",
  aligned: "Les horizons disponibles vont dans le même sens.", opposed: "Des horizons donnent des orientations opposées.", mixed: "L’orientation n’est pas confirmée sur tous les horizons.", insufficient: "Deux périodes distinctes sont nécessaires pour comparer.",
  alignedHelp: "Cet accord décrit la situation observée. Il ne garantit pas que la tendance va continuer.",
  opposedHelp: "Un repli court peut coexister avec une tendance de fond haussière, ou l’inverse. Choisissez votre horizon d’observation avant d’interpréter le signal ; le score le plus élevé ne choisit pas cet horizon à votre place.",
  mixedHelp: "Certaines périodes restent en attente. L’absence de confirmation est une information utile ; elle ne doit pas être transformée en signal d’achat ou de vente.",
  comparisonHelp: "La comparaison porte sur les périodes actuellement disponibles pour votre formule.", openComparison: "Ouvrir la comparaison détaillée", shortest: "Horizon le plus court disponible", longest: "Horizon le plus long disponible",
  followHelp: "Retrouvez cet actif et votre raisonnement lors de votre prochaine visite.", favorite: "Ajouter aux favoris", savedFavorite: "Retirer des favoris", alert: "Choisir un seuil à surveiller", journal: "Préparer ma note", passport: "Conserver cette analyse", history: "Ouvrir mes passeports", plans: "Voir les fonctions de mon pack",
  previous: "Depuis votre dernière analyse comparable", noPrevious: "Aucun passeport comparable pour cet actif, cette période et cette méthode. Les anciens passeports restent consultables dans votre historique.", priceChange: "Évolution du cours observé", notPerformance: "Évolution entre deux observations, pas un rendement de transaction.", unchanged: "Orientation inchangée", changed: "Orientation modifiée", previousReading: "Lecture enregistrée", currentReading: "Lecture actuelle",
  noCredit: "Ces repères réutilisent les données chargées, sans analyse IA supplémentaire.",
  glossary: "Comprendre les termes", support: "Support : zone où le prix a rencontré des achats. Elle peut être franchie.", resistance: "Résistance : zone où le prix a rencontré des ventes. Elle peut être franchie.", invalidation: "Invalidation : observation qui remettrait le scénario en question.",
  journalTitle: "Mon observation", journalReason: "Ce que je comprends et pourquoi", journalInvalidation: "Ce qui remettrait mon interprétation en question", journalNext: "Ce que je vérifierai lors de ma prochaine lecture", journalChoice: "Mon choix personnel : observer / attendre / autre",
};
type Copy = { [K in keyof typeof fr]: string };
const en: Copy = {
  title: "Your analysis path", intro: "Understand the reading, compare horizons, then keep a record.", understand: "Understand", compare: "Compare", follow: "Follow", next: "Next step",
  reading: "Reading for the selected timeframe", bullish: "Bullish orientation", bearish: "Bearish orientation", neutral: "Conditions need confirmation",
  loading: "Loading data for this selection…", unavailable: "A reading is not available for this selection.", stale: "The data is old: refresh before saving this reading.", refresh: "Refresh market data", details: "Read the full explanation", news: "Check the news", source: "Price source", date: "Latest data", unknown: "Not provided",
  ai: "AI reading", technical: "Technical reading", confidence: "The score describes estimated signal alignment. It is not a probability of profit.",
  aligned: "Available horizons point in the same direction.", opposed: "Some horizons point in opposite directions.", mixed: "The orientation is not confirmed across all horizons.", insufficient: "Two distinct timeframes are needed to compare.",
  alignedHelp: "This agreement describes the observed situation. It does not guarantee that the trend will continue.", opposedHelp: "A short pullback can coexist with a rising long-term trend, or the reverse. Choose your observation horizon before interpreting the signal; the highest score does not choose that horizon for you.", mixedHelp: "Some timeframes are still waiting for confirmation. Missing confirmation is useful information and should not be turned into a buy or sell signal.", comparisonHelp: "The comparison uses the timeframes currently available in your plan.", openComparison: "Open the detailed comparison", shortest: "Shortest available horizon", longest: "Longest available horizon",
  followHelp: "Return to this asset and your reasoning on your next visit.", favorite: "Add to favorites", savedFavorite: "Remove from favorites", alert: "Choose a level to watch", journal: "Prepare my note", passport: "Save this analysis", history: "Open my passports", plans: "View my plan’s features",
  previous: "Since your last comparable analysis", noPrevious: "No comparable passport for this asset, timeframe and method. Older passports remain available in your history.", priceChange: "Observed price change", notPerformance: "Movement between two observations, not a trade return.", unchanged: "Orientation unchanged", changed: "Orientation changed", previousReading: "Saved reading", currentReading: "Current reading",
  noCredit: "These guides reuse loaded data without an additional AI analysis.", glossary: "Understand the terms", support: "Support: a zone where buying has met the price. It can be broken.", resistance: "Resistance: a zone where selling has met the price. It can be broken.", invalidation: "Invalidation: an observation that would challenge the scenario.", journalTitle: "My observation", journalReason: "What I understand and why", journalInvalidation: "What would challenge my interpretation", journalNext: "What I will check on my next review", journalChoice: "My own choice: observe / wait / other",
};
const de: Copy = {
  title: "Ihr Analyseweg", intro: "Die Einschätzung verstehen, Horizonte vergleichen und die Überlegung festhalten.", understand: "Verstehen", compare: "Vergleichen", follow: "Beobachten", next: "Nächster Schritt",
  reading: "Einschätzung für den gewählten Zeitraum", bullish: "Aufwärtsorientierung", bearish: "Abwärtsorientierung", neutral: "Bedingungen noch zu bestätigen", loading: "Daten für diese Auswahl werden geladen…", unavailable: "Für diese Auswahl ist keine Einschätzung verfügbar.", stale: "Die Daten sind veraltet: vor dem Speichern aktualisieren.", refresh: "Marktdaten aktualisieren", details: "Vollständige Erklärung lesen", news: "Nachrichten prüfen", source: "Kursquelle", date: "Neueste Daten", unknown: "Nicht angegeben", ai: "KI-Einschätzung", technical: "Technische Einschätzung", confidence: "Der Wert beschreibt die geschätzte Übereinstimmung der Signale. Er ist keine Gewinnwahrscheinlichkeit.",
  aligned: "Die verfügbaren Horizonte zeigen in dieselbe Richtung.", opposed: "Einige Horizonte zeigen in entgegengesetzte Richtungen.", mixed: "Die Richtung ist nicht in allen Horizonten bestätigt.", insufficient: "Für den Vergleich sind zwei unterschiedliche Zeiträume nötig.", alignedHelp: "Diese Übereinstimmung beschreibt die beobachtete Lage. Sie garantiert keine Fortsetzung des Trends.", opposedHelp: "Ein kurzfristiger Rückgang kann mit einem langfristigen Aufwärtstrend zusammenfallen oder umgekehrt. Wählen Sie Ihren Beobachtungshorizont vor der Interpretation; der höchste Wert trifft diese Wahl nicht für Sie.", mixedHelp: "Einige Zeiträume warten noch auf Bestätigung. Eine fehlende Bestätigung ist eine wichtige Information und kein Kauf- oder Verkaufssignal.", comparisonHelp: "Verglichen werden die derzeit in Ihrem Tarif verfügbaren Zeiträume.", openComparison: "Detaillierten Vergleich öffnen", shortest: "Kürzester verfügbarer Horizont", longest: "Längster verfügbarer Horizont",
  followHelp: "Finden Sie diese Anlage und Ihre Überlegung beim nächsten Besuch wieder.", favorite: "Zu Favoriten hinzufügen", savedFavorite: "Aus Favoriten entfernen", alert: "Beobachtungsniveau wählen", journal: "Meine Notiz vorbereiten", passport: "Diese Analyse speichern", history: "Meine Pässe öffnen", plans: "Funktionen meines Tarifs ansehen", previous: "Seit Ihrer letzten vergleichbaren Analyse", noPrevious: "Kein vergleichbarer Pass für diese Anlage, diesen Zeitraum und diese Methode. Ältere Pässe bleiben im Verlauf verfügbar.", priceChange: "Beobachtete Kursänderung", notPerformance: "Bewegung zwischen zwei Beobachtungen, keine Transaktionsrendite.", unchanged: "Richtung unverändert", changed: "Richtung geändert", previousReading: "Gespeicherte Einschätzung", currentReading: "Aktuelle Einschätzung", noCredit: "Diese Orientierung nutzt geladene Daten ohne zusätzliche KI-Analyse.", glossary: "Begriffe verstehen", support: "Unterstützung: Zone, in der der Kurs auf Käufe traf. Sie kann durchbrochen werden.", resistance: "Widerstand: Zone, in der der Kurs auf Verkäufe traf. Sie kann durchbrochen werden.", invalidation: "Invalidierung: Beobachtung, die das Szenario infrage stellen würde.", journalTitle: "Meine Beobachtung", journalReason: "Was ich verstehe und warum", journalInvalidation: "Was meine Interpretation infrage stellen würde", journalNext: "Was ich bei meiner nächsten Analyse prüfe", journalChoice: "Meine eigene Wahl: beobachten / abwarten / andere",
};
const nl: Copy = {
  title: "Uw analysepad", intro: "Begrijp de lezing, vergelijk de horizons en bewaar uw redenering.", understand: "Begrijpen", compare: "Vergelijken", follow: "Volgen", next: "Volgende stap", reading: "Lezing voor de gekozen periode", bullish: "Opwaartse richting", bearish: "Neerwaartse richting", neutral: "Voorwaarden nog te bevestigen", loading: "Gegevens voor deze selectie laden…", unavailable: "Er is geen lezing beschikbaar voor deze selectie.", stale: "De gegevens zijn verouderd: vernieuw ze voordat u deze lezing bewaart.", refresh: "Marktgegevens vernieuwen", details: "Volledige uitleg lezen", news: "Nieuws controleren", source: "Koersbron", date: "Nieuwste gegevens", unknown: "Niet vermeld", ai: "AI-lezing", technical: "Technische lezing", confidence: "De score beschrijft de geschatte afstemming van signalen. Het is geen winstkans.",
  aligned: "De beschikbare horizons wijzen in dezelfde richting.", opposed: "Sommige horizons wijzen in tegengestelde richtingen.", mixed: "De richting is niet over alle horizons bevestigd.", insufficient: "Er zijn twee verschillende periodes nodig voor een vergelijking.", alignedHelp: "Deze overeenstemming beschrijft de waargenomen situatie. Ze garandeert niet dat de trend doorgaat.", opposedHelp: "Een korte terugval kan samengaan met een stijgende langetermijntrend, of omgekeerd. Kies uw observatiehorizon voordat u het signaal interpreteert; de hoogste score kiest die horizon niet voor u.", mixedHelp: "Sommige periodes wachten nog op bevestiging. Ontbrekende bevestiging is nuttige informatie en mag niet als koop- of verkoopsignaal worden voorgesteld.", comparisonHelp: "De vergelijking gebruikt de periodes die momenteel in uw pakket beschikbaar zijn.", openComparison: "Gedetailleerde vergelijking openen", shortest: "Kortste beschikbare horizon", longest: "Langste beschikbare horizon",
  followHelp: "Vind dit actief en uw redenering terug bij uw volgende bezoek.", favorite: "Aan favorieten toevoegen", savedFavorite: "Uit favorieten verwijderen", alert: "Een niveau kiezen om te volgen", journal: "Mijn notitie voorbereiden", passport: "Deze analyse bewaren", history: "Mijn paspoorten openen", plans: "Functies van mijn pakket bekijken", previous: "Sinds uw laatste vergelijkbare analyse", noPrevious: "Geen vergelijkbaar paspoort voor dit actief, deze periode en methode. Oudere paspoorten blijven in uw geschiedenis beschikbaar.", priceChange: "Waargenomen koersverandering", notPerformance: "Beweging tussen twee waarnemingen, geen transactierendement.", unchanged: "Richting ongewijzigd", changed: "Richting gewijzigd", previousReading: "Bewaarde lezing", currentReading: "Huidige lezing", noCredit: "Deze uitleg hergebruikt geladen gegevens zonder extra AI-analyse.", glossary: "Begrippen begrijpen", support: "Steun: zone waar de koers op koopinteresse stuitte. Deze kan doorbroken worden.", resistance: "Weerstand: zone waar de koers op verkoopinteresse stuitte. Deze kan doorbroken worden.", invalidation: "Invalidatie: waarneming die het scenario in twijfel zou trekken.", journalTitle: "Mijn waarneming", journalReason: "Wat ik begrijp en waarom", journalInvalidation: "Wat mijn interpretatie in twijfel zou trekken", journalNext: "Wat ik bij mijn volgende analyse zal controleren", journalChoice: "Mijn eigen keuze: observeren / afwachten / anders",
};
export const journeyCopy: Record<Lang, Copy> = { fr, en, de, nl };
export function readingLabel(value: string | null, language: Lang) {
  const c = journeyCopy[language];
  return value === "ACHETER" ? c.bullish : value === "VENDRE" ? c.bearish : value === "ATTENDRE" ? c.neutral : c.unknown;
}
export function periodLabel(period: string, language: Lang) {
  const labels: Record<Lang, string[]> = {
    fr: ["15 min", "30 min", "45 min", "1 h", "4 h", "1 jour", "1 semaine", "1 mois", "6 mois", "1 an"],
    en: ["15 min", "30 min", "45 min", "1 h", "4 h", "1 day", "1 week", "1 month", "6 months", "1 year"],
    de: ["15 Min.", "30 Min.", "45 Min.", "1 Std.", "4 Std.", "1 Tag", "1 Woche", "1 Monat", "6 Monate", "1 Jahr"],
    nl: ["15 min", "30 min", "45 min", "1 u", "4 u", "1 dag", "1 week", "1 maand", "6 maanden", "1 jaar"],
  };
  return labels[language][["15m", "30m", "45m", "1h", "4h", "1d", "1w", "1mo", "6mo", "1y"].indexOf(period)] || period;
}
