import{createSign}from'node:crypto';
import{connect}from'node:http2';

type PushMessage={title:string;body:string;url:string;eventId:string;assetKey:string};
type DeliveryResult={ok:boolean;status:number;provider:'fcm'|'apns';reason?:string};
const b64=(value:string|Buffer)=>Buffer.from(value).toString('base64url');
let fcmToken:{value:string;expiresAt:number}|null=null;

async function getFcmAccessToken(){if(fcmToken&&fcmToken.expiresAt>Date.now()+60_000)return fcmToken.value;const email=process.env.FCM_CLIENT_EMAIL,key=process.env.FCM_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!email||!key)throw new Error('fcm_not_configured');const now=Math.floor(Date.now()/1000),header=b64(JSON.stringify({alg:'RS256',typ:'JWT'})),payload=b64(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/firebase.messaging',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const signer=createSign('RSA-SHA256');signer.update(`${header}.${payload}`);signer.end();const assertion=`${header}.${payload}.${signer.sign(key).toString('base64url')}`;const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),cache:'no-store'});const data=await response.json();if(!response.ok||!data.access_token)throw new Error(data?.error_description||'fcm_oauth_failed');fcmToken={value:String(data.access_token),expiresAt:Date.now()+Number(data.expires_in||3600)*1000};return fcmToken.value;}

export async function sendFcm(token:string,message:PushMessage):Promise<DeliveryResult>{const project=process.env.FCM_PROJECT_ID;if(!project)return{ok:false,status:503,provider:'fcm',reason:'fcm_not_configured'};try{const accessToken=await getFcmAccessToken();const response=await fetch(`https://fcm.googleapis.com/v1/projects/${encodeURIComponent(project)}/messages:send`,{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({message:{token,notification:{title:message.title,body:message.body},data:{url:message.url,eventId:message.eventId,assetKey:message.assetKey}}}),cache:'no-store'});if(response.ok)return{ok:true,status:response.status,provider:'fcm'};const text=await response.text();return{ok:false,status:response.status,provider:'fcm',reason:text.slice(0,500)};}catch(e){return{ok:false,status:500,provider:'fcm',reason:e instanceof Error?e.message:'fcm_failed'};}}

function apnsJwt(){const keyId=process.env.APNS_KEY_ID,teamId=process.env.APNS_TEAM_ID,key=process.env.APNS_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!keyId||!teamId||!key)throw new Error('apns_not_configured');const header=b64(JSON.stringify({alg:'ES256',kid:keyId})),payload=b64(JSON.stringify({iss:teamId,iat:Math.floor(Date.now()/1000)}));const signer=createSign('SHA256');signer.update(`${header}.${payload}`);signer.end();const signature=signer.sign({key,dsaEncoding:'ieee-p1363'}).toString('base64url');return`${header}.${payload}.${signature}`;}

export async function sendApns(token:string,message:PushMessage):Promise<DeliveryResult>{const topic=process.env.APNS_BUNDLE_ID;if(!topic)return{ok:false,status:503,provider:'apns',reason:'apns_not_configured'};const origin=process.env.APNS_USE_SANDBOX==='true'?'https://api.sandbox.push.apple.com':'https://api.push.apple.com';return new Promise(resolve=>{let client:any;try{client=connect(origin);const req=client.request({':method':'POST',':path':`/3/device/${encodeURIComponent(token)}`,authorization:`bearer ${apnsJwt()}`,'apns-topic':topic,'apns-push-type':'alert','apns-priority':'10','content-type':'application/json'});let status=500,body='';req.on('response',(headers:any)=>{status=Number(headers[':status']||500);});req.setEncoding('utf8');req.on('data',(chunk:string)=>body+=chunk);req.on('end',()=>{client.close();resolve({ok:status>=200&&status<300,status,provider:'apns',...(status>=300?{reason:body.slice(0,500)}:{})});});req.on('error',(error:Error)=>{client.close();resolve({ok:false,status:500,provider:'apns',reason:error.message});});req.end(JSON.stringify({aps:{alert:{title:message.title,body:message.body},sound:'default'},url:message.url,eventId:message.eventId,assetKey:message.assetKey}));}catch(e){client?.close?.();resolve({ok:false,status:500,provider:'apns',reason:e instanceof Error?e.message:'apns_failed'});}});}
