import {getBillingAccount,saveBillingState,billingHost} from './plan-billing-store';
import {billingConfig} from './plan-billing-config';
import {stripeRequest,sameOrigin,verifyStripeEvent,subscriptionAccess} from './plan-billing-core';
export async function checkout(r:Request,portal=false){try{if(!sameOrigin(r))return Response.json({error:'forbidden'},{status:403});const a=await getBillingAccount();if(!a)return Response.redirect(new URL('/account',r.url),303);const c=billingConfig();if(!c.ready)return Response.redirect(new URL('/pricing?billing=unavailable',r.url),303);const origin=new URL(r.url).origin;
 if(portal||(a.subscriptionId&&['active','trialing','past_due'].includes(a.status.toLowerCase()))){if(!a.customerId)return Response.redirect(new URL('/pricing?billing=no-subscription',origin),303);const session=await stripeRequest('billing_portal/sessions',new URLSearchParams({customer:a.customerId,return_url:origin+'/account'}));return Response.redirect(session.url,303);}
 const form=await r.formData(),plan=String(form.get('plan'));if(!['pro','expert','trader_plus'].includes(plan))return Response.json({error:'invalid_plan'},{status:400});const selected=plan==='pro'?'pro':'expert';const body=new URLSearchParams({mode:'subscription','line_items[0][price]':selected==='pro'?c.pro:c.expert,'line_items[0][quantity]':'1',client_reference_id:a.id,'subscription_data[metadata][user_id]':a.id,'subscription_data[metadata][email]':a.email,'subscription_data[metadata][application]':'cockpit-marches-ai','subscription_data[metadata][hosting]':billingHost,'metadata[application]':'cockpit-marches-ai','metadata[hosting]':billingHost,success_url:origin+'/pricing?billing=processing',cancel_url:origin+'/pricing?billing=cancelled',integration_identifier:'cockpitplans_qmrztkps'});if(a.customerId)body.set('customer',a.customerId);else body.set('customer_email',a.email);const session=await stripeRequest('checkout/sessions',body,`cockpit:${billingHost}:${a.id}:${selected}:${Math.floor(Date.now()/60000)}`);return Response.redirect(session.url,303);
 }catch{return Response.json({error:'billing_unavailable'},{status:503});}}
export async function billingWebhook(r:Request){const c=billingConfig();if(!c.ready)return Response.json({error:'billing_unavailable'},{status:503});let event:any;try{const raw=await r.text();if(raw.length>1000000)return Response.json({error:'too_large'},{status:413});event=await verifyStripeEvent(raw,r.headers.get('stripe-signature')||'',process.env.STRIPE_WEBHOOK_SECRET!);}catch{return Response.json({error:'invalid_signature'},{status:400});}
 if(event.livemode!==c.live)return Response.json({received:true,ignored:true});
 const type=event.type||'',object=event.data?.object;let subId:string|undefined;
 if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(type))subId=typeof object?.subscription==='string'?object.subscription:object?.subscription?.id;
 else if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(type))subId=object?.id;
 else if(['invoice.paid','invoice.payment_failed'].includes(type)){const s=object?.parent?.subscription_details?.subscription||object?.subscription;subId=typeof s==='string'?s:s?.id;}
 if(!subId||!/^sub_[A-Za-z0-9]+$/.test(subId))return Response.json({received:true});
 try{const sub=await stripeRequest('subscriptions/'+encodeURIComponent(subId)+'?expand%5B%5D=latest_invoice');if(sub.metadata?.application!=='cockpit-marches-ai'||(sub.metadata.hosting||'sites')!==billingHost)return Response.json({received:true,ignored:true});const userId=sub.metadata.user_id||(billingHost==='sites'?sub.metadata.email:null);if(!userId)return Response.json({received:true,ignored:true});const state=subscriptionAccess(sub,c.pro,c.expert);await saveBillingState({userId,subscriptionId:sub.id,customerId:typeof sub.customer==='string'?sub.customer:sub.customer.id,plan:state.plan,status:state.status,priceId:sub.items?.data?.[0]?.price?.id||null,currentPeriodEnd:sub.items?.data?.[0]?.current_period_end?sub.items.data[0].current_period_end*1000:null,cancelAtPeriodEnd:!!sub.cancel_at_period_end,eventAt:Number(event.created)*1000});return Response.json({received:true});}catch{return Response.json({error:'billing_unavailable'},{status:503});}}
