import AccountDetails from '@/components/account-details';
import {getBillingAccount} from '@/lib/plan-billing-store';
import {billingPublicStatus} from '@/lib/plan-billing-config';
import Link from'next/link';
import{accountCopy}from'@/lib/account-copy';
import{requirePageMembership}from'@/lib/access-control';
import{getUsageSummary}from'@/lib/usage-store';
export const dynamic='force-dynamic';
export default async function SubscriptionPage(){const{membership:account}=await requirePageMembership('/account/subscription'),usage=await getUsageSummary(account);const [billing,billingAccount]=await Promise.all([billingPublicStatus(),getBillingAccount()]);const copy=accountCopy(account.locale),ai=usage.features.AI_INSTANT_ANALYSIS;return <main className="accountShell"><Link href="/account">← {copy.account}</Link><section className="accountPanel"><h1>{copy.subscription}</h1><p>{copy.manageSubscription}</p><dl className="membershipFacts"><div><dt>{copy.plan}</dt><dd>{account.plan}</dd></div><div><dt>{copy.status}</dt><dd>{account.subscriptionStatus}</dd></div><div><dt>{copy.role}</dt><dd>{account.role}</dd></div></dl><h2>{copy.usage}</h2><dl className="membershipFacts"><div><dt>{copy.aiAnalyses}</dt><dd>{ai.limit==null?copy.unlimited:`${ai.used} / ${ai.limit}`}</dd></div><div><dt>{copy.resets}</dt><dd>{new Date(usage.windowEnd).toLocaleDateString(account.locale,{timeZone:'UTC'})}</dd></div></dl><Link className="accountButton" href="/pricing">{copy.offers}</Link><AccountDetails email={account.email} displayName={account.displayName} plan={account.plan} status={account.subscriptionStatus} periodEnd={account.currentPeriodEnd} cancelAtEnd={account.cancelAtPeriodEnd} portalAvailable={billing.ready && !!billingAccount?.customerId}/><p className="accountSecure">{copy.secure}</p></section></main>}
