import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'update_controller.dart';
Future<void> showUpdates(BuildContext context,UpdateController updates,Future<void>Function() refresh)=>showModalBottomSheet<void>(context:context,isScrollControlled:true,useSafeArea:true,builder:(_)=>UpdateSheet(updates:updates,refresh:refresh));
class UpdateSheet extends StatefulWidget{const UpdateSheet({super.key,required this.updates,required this.refresh});final UpdateController updates;final Future<void>Function() refresh;@override State<UpdateSheet> createState()=>_UpdateSheetState();}
class _UpdateSheetState extends State<UpdateSheet>{
 bool refreshing=false;String? actionError;
 Future<void> refresh()async{setState(()=>refreshing=true);try{await widget.updates.refreshData(widget.refresh);if(mounted)setState(()=>actionError=null);}catch(_){if(mounted)setState(()=>actionError='Actualisation impossible. Votre écran actuel est conservé.');}finally{if(mounted)setState(()=>refreshing=false);}}
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:widget.updates,builder:(context,_){final u=widget.updates;return SizedBox(height:MediaQuery.sizeOf(context).height*.8,child:ListView(padding:const EdgeInsets.all(24),children:[Row(children:[Expanded(child:Text('Nouveautés et mises à jour',style:Theme.of(context).textTheme.titleLarge)),IconButton(tooltip:'Fermer',onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close))]),const Text('Application ${UpdateController.installedVersion} · ${UpdateController.installedBuild}'),Text('Services : ${u.serverVersion??'vérification en attente'}'),const SizedBox(height:12),const Text('Vérification automatique toutes les 5 minutes et au retour dans l’application. Aucun redémarrage forcé.'),Wrap(spacing:12,children:[OutlinedButton.icon(onPressed:u.checking?null:()=>u.check(),icon:const Icon(Icons.sync),label:Text(u.checking?'Vérification…':'Vérifier maintenant')),FilledButton.icon(onPressed:refreshing?null:refresh,icon:const Icon(Icons.refresh),label:Text(refreshing?'Actualisation…':'Actualiser les données'))]),if(u.error!=null)Text(u.error!),if(actionError!=null)Text(actionError!),if(u.dataAvailable)const Text('Une nouvelle version des services est disponible.'),if(u.binaryAvailable)...[const Text('Une nouvelle version de l’application est disponible.'),if(u.storeUrl!=null)FilledButton(onPressed:()async{try{final ok=await launchUrl(u.storeUrl!,mode:LaunchMode.externalApplication);if(!ok&&mounted)setState(()=>actionError='Impossible d’ouvrir la boutique.');}catch(_){if(mounted)setState(()=>actionError='Impossible d’ouvrir la boutique.');}},child:const Text('Ouvrir la boutique'))else const Text('Le lien de distribution sera ajouté après publication.')],const Divider(),...u.releases.map((r)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${r.version} · ${r.date}',style:Theme.of(context).textTheme.titleMedium),...r.notes.map((n)=>Padding(padding:const EdgeInsets.only(top:8),child:Text('• $n'))),const Divider()])),Text('À venir — en préparation',style:Theme.of(context).textTheme.titleMedium),...u.upcoming.map((n)=>Text('• $n'))]));});
}
