import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../../core/api/api_client.dart';
import '../data/mobile_session_repository.dart';
import '../../../app_shell.dart';
import '../../../demo_app.dart';

class MobileConnectionGate extends StatefulWidget{const MobileConnectionGate({super.key,required this.apiBaseUrl});final String apiBaseUrl;@override State<MobileConnectionGate> createState()=>_MobileConnectionGateState();}
class _MobileConnectionGateState extends State<MobileConnectionGate>{final session=MobileSessionRepository();final controller=TextEditingController();bool loading=true,connecting=false;String? error;String? token;
 @override void initState(){super.initState();_restore();}
 Future<void> _restore()async{final saved=await session.readToken();if(saved!=null&&saved.isNotEmpty){final ok=await _validate(saved);if(ok){ApiClient.sessionBearerToken=saved;token=saved;}else await session.clear();}if(mounted)setState(()=>loading=false);}
 Future<bool> _validate(String value)async{try{final api=ApiClient(baseUrl:widget.apiBaseUrl,bearerToken:value),json=await api.getJson('/api/me');return json['authenticated']==true;}catch(_){return false;}}
 Future<void> _connect()async{final code=controller.text.replaceAll(RegExp(r'\D'),'');if(code.length!=8){setState(()=>error='Saisissez le code à 8 chiffres affiché dans la WebApp.');return;}setState((){connecting=true;error=null;});try{final value=await session.claimPairingCode(widget.apiBaseUrl,code),ok=await _validate(value);if(!ok)throw Exception('session_invalid');await session.saveToken(value);ApiClient.sessionBearerToken=value;if(mounted)setState((){token=value;connecting=false;});}catch(_){if(mounted)setState((){connecting=false;error='Code invalide, expiré ou déjà utilisé. Générez un nouveau code dans la WebApp.';});}}
 void _openDemo()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DemoMobileShell(apiBaseUrl:widget.apiBaseUrl)));
 @override Widget build(BuildContext context){if(loading)return const MaterialApp(home:Scaffold(body:Center(child:CircularProgressIndicator())));if(token!=null)return CockpitMarketsApp(apiBaseUrl:widget.apiBaseUrl);return MaterialApp(debugShowCheckedModeBanner:false,themeMode:ThemeMode.dark,darkTheme:ThemeData(brightness:Brightness.dark,useMaterial3:true),home:Scaffold(appBar:AppBar(title:const Text('Cockpit Marchés AI')),body:ListView(padding:const EdgeInsets.all(24),children:[const Icon(Icons.phonelink_lock,size:56),const SizedBox(height:20),Text('Connecter cette application',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:10),const Text('Dans Chrome, ouvrez cockpit-march-s-ai.vercel.app/mobile-connect, connectez-vous puis générez un code à 8 chiffres. Le code expire après 5 minutes et ne fonctionne qu’une seule fois.'),const SizedBox(height:20),TextField(controller:controller,keyboardType:TextInputType.number,inputFormatters:[FilteringTextInputFormatter.digitsOnly,LengthLimitingTextInputFormatter(8)],textAlign:TextAlign.center,style:const TextStyle(fontSize:28,letterSpacing:6),autocorrect:false,enableSuggestions:false,decoration:const InputDecoration(labelText:'Code à 8 chiffres',hintText:'12345678',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton.icon(onPressed:connecting?null:_connect,icon:const Icon(Icons.link),label:Text(connecting?'Connexion…':'Appairer ce téléphone')),const SizedBox(height:10),OutlinedButton.icon(onPressed:_openDemo,icon:const Icon(Icons.visibility_outlined),label:const Text('Continuer en démo sans compte')),const SizedBox(height:6),const Text('Le mode démo donne accès uniquement aux fonctions publiques : Cockpit, Marchés, Indicateurs et Signaux. Les données personnelles restent protégées.'),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),const SizedBox(height:20),const Text('Votre mot de passe Web n’est jamais envoyé ni stocké dans l’application mobile. Seul un jeton de session signé est conservé dans le stockage sécurisé du téléphone.')])));}
 @override void dispose(){controller.dispose();super.dispose();}}
