import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const files=execFileSync('git',['ls-files','--cached','--others','--exclude-standard','-z'],{encoding:'utf8'}).split('\0').filter(p=>p&&p!=='lib/build-version.ts'&&/^(app|components|lib|public|worker|build|scripts)\//.test(p)).sort();
const hash=createHash('sha256');
for(const path of files)if(existsSync(path)){hash.update(path+'\0');hash.update(readFileSync(path));}
const id=hash.digest('hex').slice(0,16);
writeFileSync('lib/build-version.ts',`// Generated by scripts/stamp-release.mjs before building.\nexport const BUILD_ID = ${JSON.stringify(id)};\n`);
console.log(`Release fingerprint: ${id}`);
