'use client';
import{useEffect,useMemo,useState}from'react';

type Row={key:string;symbol:string;name:string;kind:string;price?:number|null;signal?:string|null};

export default function WatchlistPage(){
 const[rows,setRows]=useState<Row[]>([]),[watchlist,setWatchlist]=useState<string[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const[scanner,snapshot]=await Promise.all([fetch('/api/scanner').then(r=>r.json()),fetch('/api/user-sync/snapshot').then(async r=>({ok:r.ok,status:r.status,data:await r.json()}))]);setRows(scanner.rows||[]);if(!snapshot.ok)throw new Error(snapshot.data?.error||`sync_${snapshot.status}`);setWatchlist(snapshot.data?.snapshot?.watchlist||[]);}catch(e){setError(e instanceof Error?e.message:'Erreur de synchronisation');}finally{setLoading(false)}})();},[]);
 const selected=useMemo(()=>new Set(watchlist),[watchlist]);
 const toggle=async(key:string)=>{const next=selected.has(key)?watchlist.filter(x=>x!==key):[...watchlist,key];setWatchlist(next);setSaving(true);setError('');try{const r=await fetch('/api/user-sync/watchlist',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetKeys:next})}),data=await r.json();if(!r.ok)throw new Error(data?.error||'save_failed');setWatchlist(data.watchlist||next);}catch(e){setError(e instanceof Error?e.message:'Erreur');}finally{setSaving(false)}};
 return <main style={{maxWidth:980,margin:'32px auto',padding:20,fontFamily:'system-ui'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><p style={{margin:0,opacity:.65}}>COCKPIT MARCHÉS AI</p><h1 style={{marginTop:4}}>Watchlist synchronisée</h1><p>Les favoris enregistrés ici utilisent le même compte et le même backend que l’application Flutter.</p></div><a href="/">Retour au cockpit</a></header>{loading&&<p>Chargement…</p>}{error&&<div style={{padding:14,border:'1px solid #8b3a3a',borderRadius:10,margin:'16px 0'}}><b>Synchronisation indisponible</b><p style={{marginBottom:0}}>{error==='storage_not_configured'?'Le store durable utilisateur doit être configuré avant d’activer les favoris multi-appareils.':error}</p></div>}<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}>{rows.map(row=><article key={row.key} style={{border:'1px solid #344',borderRadius:12,padding:14}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><b>{row.symbol}</b><div style={{opacity:.7,fontSize:13}}>{row.name} · {row.kind}</div></div><button disabled={saving||!!error} onClick={()=>toggle(row.key)} aria-pressed={selected.has(row.key)}>{selected.has(row.key)?'★ Favori':'☆ Ajouter'}</button></div><div style={{marginTop:12,display:'flex',justifyContent:'space-between'}}><span>{typeof row.price==='number'?row.price.toLocaleString():'—'}</span><span>{row.signal||'NEUTRE'}</span></div></article>)}</section></main>;
}
