'use client';
import Link from'next/link';
import{useState}from'react';
import{PLAN_ENTITLEMENTS,type Feature}from'@/lib/entitlements';
import type{CommercialPlan,SupportedLocale}from'@/lib/account-types';
import'./pricing.css';
const plans:CommercialPlan[]=['DISCOVERY','PRO','EXPERT'];
const prices:Record<CommercialPlan,number>={DISCOVERY:0,PRO:24,EXPERT:49};
const copy={fr:{title:'Choisissez votre niveau d’analyse',subtitle:'Des droits clairs, contrôlés côté serveur, sans fonction artificiellement déverrouillée.',month:'/ mois',current:'Commencer',account:'Mon compte',back:'Retour au cockpit'},en:{title:'Choose your analysis level',subtitle:'Clear server-controlled access with no artificially unlocked feature.',month:'/ month',current:'Get started',account:'My account',back:'Back to cockpit'},de:{title:'Wählen Sie Ihr Analyselevel',subtitle:'Klare serverseitig kontrollierte Rechte ohne künstlich freigeschaltete Funktionen.',month:'/ Monat',current:'Starten',account:'Mein Konto',back:'Zurück zum Cockpit'},nl:{title:'Kies uw analyseniveau',subtitle:'Duidelijke servergestuurde rechten zonder kunstmatig ontgrendelde functies.',month:'/ maand',current:'Beginnen',account:'Mijn account',back:'Terug naar cockpit'}}as const;
const featureLabels:Record<SupportedLocale,Record<Feature,string>>={
 fr:{DASHBOARD_BASIC:'Tableau de bord essentiel',ALL_ASSETS:'Tous les actifs',REALTIME_REFRESH:'Actualisation temps réel',FULL_TIMEFRAMES:'Toutes les périodes',TECHNICAL_INDICATORS:'Indicateurs techniques',ICHIMOKU_ADVANCED:'Ichimoku avancé',FORECASTS:'Prévisions',MULTI_TIMEFRAME:'Multi-timeframes',AI_INSTANT_ANALYSIS:'Analyse IA approfondie',DECISION_PASSPORTS:'Passeports de décision',ALERTS:'Alertes',PAPER_TRADING:'Paper Trading',EXTENDED_HISTORY:'Historique étendu',ADMIN_PANEL:'Administration'},
 en:{DASHBOARD_BASIC:'Essential dashboard',ALL_ASSETS:'All assets',REALTIME_REFRESH:'Real-time refresh',FULL_TIMEFRAMES:'All timeframes',TECHNICAL_INDICATORS:'Technical indicators',ICHIMOKU_ADVANCED:'Advanced Ichimoku',FORECASTS:'Forecasts',MULTI_TIMEFRAME:'Multi-timeframes',AI_INSTANT_ANALYSIS:'Advanced AI analysis',DECISION_PASSPORTS:'Decision passports',ALERTS:'Alerts',PAPER_TRADING:'Paper Trading',EXTENDED_HISTORY:'Extended history',ADMIN_PANEL:'Administration'},
 de:{DASHBOARD_BASIC:'Basis-Dashboard',ALL_ASSETS:'Alle Assets',REALTIME_REFRESH:'Echtzeit-Aktualisierung',FULL_TIMEFRAMES:'Alle Zeiträume',TECHNICAL_INDICATORS:'Technische Indikatoren',ICHIMOKU_ADVANCED:'Erweitertes Ichimoku',FORECASTS:'Prognosen',MULTI_TIMEFRAME:'Multi-Timeframes',AI_INSTANT_ANALYSIS:'Vertiefte KI-Analyse',DECISION_PASSPORTS:'Entscheidungspässe',ALERTS:'Warnungen',PAPER_TRADING:'Paper Trading',EXTENDED_HISTORY:'Erweiterter Verlauf',ADMIN_PANEL:'Administration'},
 nl:{DASHBOARD_BASIC:'Essentieel dashboard',ALL_ASSETS:'Alle activa',REALTIME_REFRESH:'Realtime verversing',FULL_TIMEFRAMES:'Alle periodes',TECHNICAL_INDICATORS:'Technische indicatoren',ICHIMOKU_ADVANCED:'Geavanceerde Ichimoku',FORECASTS:'Prognoses',MULTI_TIMEFRAME:'Multi-timeframes',AI_INSTANT_ANALYSIS:'Uitgebreide AI-analyse',DECISION_PASSPORTS:'Beslissingspaspoorten',ALERTS:'Waarschuwingen',PAPER_TRADING:'Paper Trading',EXTENDED_HISTORY:'Uitgebreide historie',ADMIN_PANEL:'Administratie'},
};
export default function PricingPage(){const[locale,setLocale]=useState<SupportedLocale>('fr'),text=copy[locale];return <main className="pricingShell"><header><Link href="/">← {text.back}</Link><nav>{(['fr','en','de','nl']as const).map(value=><button className={locale===value?'active':''} onClick={()=>setLocale(value)} key={value}>{value.toUpperCase()}</button>)}</nav><Link href="/account">{text.account}</Link></header><section className="pricingHero"><p>DISCOVERY · PRO · EXPERT</p><h1>{text.title}</h1><span>{text.subtitle}</span></section><section className="pricingGrid">{plans.map(plan=><article key={plan} className={plan==='PRO'?'featured':''}><h2>{plan}</h2><p className="price"><b>{prices[plan]} €</b><span>{text.month}</span></p><ul>{PLAN_ENTITLEMENTS[plan].features.map(feature=><li key={feature}>✓ {featureLabels[locale][feature]}</li>)}</ul><Link href="/account/subscription">{text.current}</Link></article>)}</section></main>}
